// Seed data with accurate coordinates from OpenStreetMap
// Generated: 2026-04-17T19:29:46.864Z

export const categories = [
  {
    "id": 1,
    "name": "Kneipen",
    "color": "#9B2915",
    "icon": "bar"
  },
  {
    "id": 2,
    "name": "Essen",
    "color": "#3B6D11",
    "icon": "food"
  },
  {
    "id": 3,
    "name": "Nightlife",
    "color": "#2c2c2a",
    "icon": "night"
  },
  {
    "id": 4,
    "name": "Sehenswürdigkeiten",
    "color": "#C2185B",
    "icon": "sight"
  },
  {
    "id": 5,
    "name": "Hotel",
    "color": "#E5A038",
    "icon": "hotel"
  },
  {
    "id": 6,
    "name": "Neu",
    "color": "#6B7280",
    "icon": "star"
  },
  {
    "id": 9,
    "name": "Toiletten",
    "color": "#1976D2",
    "icon": "wc"
  }
]

export const locations = [
  {
    "category_id": 5,
    "name": "Hotel Niky",
    "meta": "Neofit Rilski 16 · +359 2 952 3058",
    "rating": null,
    "price_range": null,
    "lat": 42.690654,
    "lng": 23.3165775
  },
  {
    "category_id": 4,
    "name": "Alexander-Newski-Kathedrale",
    "meta": "Wahrzeichen · goldene Kuppeln",
    "rating": null,
    "price_range": null,
    "lat": 42.6958124,
    "lng": 23.3327934,
    "description": "Sofias bekanntestes Wahrzeichen und eine der größten orthodoxen Kathedralen der Welt. Erbaut 1882–1912 zum Gedenken an die russischen Soldaten des Befreiungskriegs 1877/78. Die vergoldeten Kuppeln sind von fast überall in der Innenstadt sichtbar.",
    "entry_fee": "Kostenlos (Krypta-Museum: 3 BGN)",
    "visit_duration": "20–30 Min",
    "best_time_to_visit": "Früh morgens (weniger Touristen) oder abends für goldene Kuppeln im Licht",
    "photo_allowed": "Innen verboten",
    "guided_tours": "Keine offiziellen Führungen",
    "key_features": "[\"Goldene Kuppeln\", \"Krypta-Museum mit Ikonensammlung\", \"Größte Kirche Bulgariens\"]",
    "dress_code": "Schultern und Knie bedeckt",
    "service_times": "tägl. 7:00–19:00"
  },
  {
    "category_id": 4,
    "name": "Rotunde Hl. Georg",
    "meta": "4. Jh. · älteste Kirche Sofias",
    "rating": null,
    "price_range": null,
    "lat": 42.696892,
    "lng": 23.322882,
    "description": "Die älteste erhaltene Kirche Sofias stammt aus dem 4. Jahrhundert und liegt versteckt im Innenhof des Sheraton-Hotels — direkt neben dem Präsidentenpalast. Die frühchristlichen Fresken aus dem 10.–14. Jahrhundert sind einzigartig. Ein absolut unterschätztes Highlight.",
    "entry_fee": "Kostenlos",
    "visit_duration": "15–20 Min",
    "best_time_to_visit": "Wochentags vor 12 Uhr",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Frühchristliche Fresken 10.–14. Jh.\", \"Ältestes Gebäude Sofias (4. Jh.)\", \"Versteckt im Sheratonhof\"]",
    "dress_code": "Schultern bedeckt",
    "service_times": "Mo–Sa 8:00–17:00, So 10:30–17:00"
  },
  {
    "category_id": 4,
    "name": "Sveta Sofia Kirche",
    "meta": "6. Jh. · Namensgeberin der Stadt",
    "rating": null,
    "price_range": null,
    "lat": 42.6961,
    "lng": 23.3325,
    "description": "Die frühchristliche Basilika aus dem 6. Jahrhundert gab der Stadt ihren Namen. Unter osmanischer Herrschaft als Moschee genutzt, heute wieder orthodoxe Kirche. Vor dem Eingang brennt die ewige Flamme am Grab des Unbekannten Soldaten.",
    "entry_fee": "Kostenlos",
    "visit_duration": "15 Min",
    "best_time_to_visit": "Tagsüber, morgens weniger Andrang",
    "photo_allowed": "Innen eingeschränkt",
    "guided_tours": "Keine",
    "key_features": "[\"Basilika aus dem 6. Jh.\", \"Namensgeberin der Stadt Sofia\", \"Ewige Flamme vor dem Eingang\"]",
    "dress_code": "Schultern bedeckt",
    "service_times": "tägl. 7:00–18:30"
  },
  {
    "category_id": 4,
    "name": "Sveta Nedelya Kathedrale",
    "meta": "Zentraler Platz · Bombengeschichte",
    "rating": null,
    "price_range": null,
    "lat": 42.6967146,
    "lng": 23.3213884,
    "description": "Die imposante Kathedrale am zentralen Sveta-Nedelya-Platz wurde 1925 Ziel eines kommunistischen Bombenanschlags — über 150 Tote, darunter fast das gesamte Militärkabinett. Die heutige Kirche ist ein Wiederaufbau und gilt als geografisches Herz der Stadt.",
    "entry_fee": "Kostenlos",
    "visit_duration": "15 Min",
    "best_time_to_visit": "Abends für Atmosphäre am beleuchteten Platz",
    "photo_allowed": "Innen verboten",
    "guided_tours": "Keine",
    "key_features": "[\"Geografisches Zentrum Sofias\", \"Bombenanschlag-Geschichte 1925\", \"Byzantinische Mosaike\"]",
    "dress_code": "Schultern und Knie bedeckt",
    "service_times": "tägl. 7:00–19:00"
  },
  {
    "category_id": 4,
    "name": "Banya Bashi Moschee",
    "meta": "16. Jh. · über heißen Quellen",
    "rating": null,
    "price_range": null,
    "lat": 42.6995002,
    "lng": 23.322572,
    "description": "Die einzige noch aktive Moschee Sofias wurde 1576 über natürlichen Thermalquellen erbaut — daher der Name 'Banya Bashi' (viele Bäder). An kühlen Tagen steigt der Dampf der 73°C heißen Quellen sichtbar um das Gebäude auf. Direkt daneben die kostenlosen öffentlichen Wasserhähne.",
    "entry_fee": "Kostenlos (außerhalb der Gebetszeiten)",
    "visit_duration": "10–15 Min",
    "best_time_to_visit": "Zwischen den Gebetszeiten",
    "photo_allowed": "Nur Außenbereich",
    "guided_tours": "Keine",
    "key_features": "[\"Einzige aktive Moschee Sofias\", \"Osmanische Architektur 1576\", \"Heiße Thermalquellen darunter\"]",
    "dress_code": "Kopftuch für Frauen, Schuhe ausziehen",
    "service_times": "Gebet 5× täglich; Besuch außerhalb möglich"
  },
  {
    "category_id": 4,
    "name": "Russische Kirche St. Nikolaus",
    "meta": "Zwiebelkuppeln · Moskauer Stil",
    "rating": null,
    "price_range": null,
    "lat": 42.695694,
    "lng": 23.328935,
    "description": "Die 1914 eingeweihte russisch-orthodoxe Kirche mit ihren grünen und goldenen Zwiebeltürmen ist eine der fotogensten Sehenswürdigkeiten Sofias. Im Keller soll das Grab des ersten Bischofs Wunderheilungen bewirken — Einheimische hinterlassen dort Zettel mit Wünschen.",
    "entry_fee": "Kostenlos",
    "visit_duration": "15 Min",
    "best_time_to_visit": "Goldene Stunde morgens oder abends für beste Fotos",
    "photo_allowed": "Außen erlaubt, innen eingeschränkt",
    "guided_tours": "Keine",
    "key_features": "[\"Grüne Zwiebeltürme\", \"Wunschzettel-Keller mit Bischofsgrab\", \"Russisch-zaristischer Baustil 1914\"]",
    "dress_code": "Schultern bedeckt",
    "service_times": "tägl. 8:00–18:00"
  },
  {
    "category_id": 4,
    "name": "Ivan Vazov Nationaltheater",
    "meta": "Neoklassizismus · abends beleuchtet",
    "rating": null,
    "price_range": null,
    "lat": 42.6944,
    "lng": 23.328,
    "description": "Das 1907 eröffnete Nationaltheater ist das prächtigste Gebäude Sofias — ein neoklassizistischer Palast, der abends in goldenem Licht erstrahlt. Direkt davor liegt der Crystal Garden. Auch ohne Vorstellung lohnt sich der Platz für eine Pause und beste Fotokulisse.",
    "entry_fee": "Außen kostenlos · Vorstellungen 15–40 BGN",
    "visit_duration": "10 Min (Außen), 2–3 Std (Vorstellung)",
    "best_time_to_visit": "Abends für die spektakuläre Beleuchtung",
    "photo_allowed": "Außen erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Neoklassizistischer Palastbau 1907\", \"Spektakuläre Abendbeleuchtung\", \"Kulturzentrum der Stadt\"]",
    "dress_code": "Für Vorstellungen: gepflegt",
    "service_times": "Vorstellungen meist 19:00"
  },
  {
    "category_id": 4,
    "name": "Ancient Serdica (Ruinen)",
    "meta": "Römerzeit · frei zugänglich",
    "rating": null,
    "price_range": null,
    "lat": 42.699635,
    "lng": 23.324990,
    "description": "Direkt unter den Straßen Sofias liegen die Überreste der römischen Stadt Serdica (2.–4. Jh.), in der Kaiser Konstantin der Große zeitweise residierte. Die Ruinen sind im Untergeschoss der Serdika-Metro-Station und im Freien zwischen Sheraton und Präsidentenpalast zu besichtigen.",
    "entry_fee": "Kostenlos",
    "visit_duration": "20–30 Min",
    "best_time_to_visit": "Tagsüber",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Römerstadt 2.–4. Jh.\", \"Kaiser Konstantin residierte hier\", \"Teils in Metro-Station Serdika\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Freiluftbereich: immer · Metro-Bereich: tägl. 5:30–24:00"
  },
  {
    "category_id": 4,
    "name": "Mineralbad & Stadtmuseum",
    "meta": "Jugendstil · Gratis-Heilquellen",
    "rating": null,
    "price_range": null,
    "lat": 42.699226,
    "lng": 23.323796,
    "description": "Das im Jugendstil erbaute öffentliche Mineralbad (1913) beherbergt heute das Stadthistorische Museum. Nebenan sprudeln kostenlose öffentliche Wasserhähne mit 73°C heißem Mineralwasser — Einheimische füllen dort täglich ihre Kanister. Ein typisch sofiotisches Bild.",
    "entry_fee": "Museum: 6 BGN · Mineralwasser: kostenlos",
    "visit_duration": "30–45 Min (Museum)",
    "best_time_to_visit": "Wochentags morgens",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Kostenlose heiße Mineralquellen (73°C)\", \"Jugendstil-Bau 1913\", \"Stadthistorisches Museum\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Di–So 10:00–18:00, Mo geschlossen"
  },
  {
    "category_id": 4,
    "name": "Vitosha Boulevard",
    "meta": "Flaniermeile · Fußgängerzone",
    "rating": null,
    "price_range": null,
    "lat": 42.694215,
    "lng": 23.320409,
    "description": "Die Fußgängerzone 'Vitosha' ist Sofias Prachtstraße — hier flaniert, shoppt und trifft man sich. Vom NDK-Palast im Süden bis zum Sveta-Nedelya-Platz im Norden, mit Blick auf den gleichnamigen Berg. Die Café-Terrassen im Mai sind Pflicht.",
    "entry_fee": "Kostenlos",
    "visit_duration": "1–2 Std",
    "best_time_to_visit": "Nachmittags und abends",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Hauptfußgängerzone Sofias\", \"Café-Terrassen & Shops\", \"Blick auf den Vitosha-Berg\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Geschäfte tägl. 10:00–21:00"
  },
  {
    "category_id": 4,
    "name": "Crystal Garden",
    "meta": "Stadtpark · Touren-Treffpunkt",
    "rating": null,
    "price_range": null,
    "lat": 42.6945024,
    "lng": 23.3296514,
    "description": "Der Kristallgarten direkt vor dem Nationaltheater ist Sofias beliebtester kleiner Park — mit Brunnen, Bänken und abends dem goldenen Glanz des Theatergebäudes als Kulisse. Hier startet täglich die kostenlose Sofia Free Tour (11:00 und 18:00 Uhr).",
    "entry_fee": "Kostenlos",
    "visit_duration": "15–20 Min",
    "best_time_to_visit": "Abends (Beleuchtung des Nationaltheaters)",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Sofia Free Tour: tägl. 11:00 & 18:00 (kostenlos, Trinkgeld)",
    "key_features": "[\"Startpunkt der kostenlosen Sofia Free Tour\", \"Brunnen vor dem Nationaltheater\", \"Beliebtester Treffpunkt der Stadt\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Immer geöffnet"
  },
  {
    "category_id": 4,
    "name": "Zentralsynagoge",
    "meta": "Größte Sephardischer Europas",
    "rating": null,
    "price_range": null,
    "lat": 42.700221,
    "lng": 23.320933,
    "description": "Die 1909 eingeweihte Sofioter Synagoge ist eine der größten in Europa und eines der schönsten Jugendstilgebäude der Stadt. Der 2,2-Tonnen-Kronleuchter im Inneren ist beeindruckend. Bulgarien rettete als einziges Land der Achsenmächte alle seine jüdischen Mitbürger vor der Deportation.",
    "entry_fee": "5 BGN",
    "visit_duration": "30 Min",
    "best_time_to_visit": "Wochentags morgens",
    "photo_allowed": "Erlaubt (kein Blitz)",
    "guided_tours": "Auf Anfrage",
    "key_features": "[\"2,2-Tonnen-Kronleuchter\", \"Wiener Sezessionsstil 1909\", \"Museum zur Rettung der bulgarischen Juden im WWII\"]",
    "dress_code": "Kippa für Männer (wird gestellt)",
    "service_times": "Mo–Fr 9:00–16:30, So 9:00–13:00"
  },
  {
    "category_id": 4,
    "name": "National Palace of Culture (NDK)",
    "meta": "Kongresszentrum · modernes Wahrzeichen",
    "rating": null,
    "price_range": null,
    "lat": 42.6847601,
    "lng": 23.3189417,
    "description": "Der NDK (Nationalen Kulturpalast) ist Sofias brutalistisches Wahrzeichen — erbaut 1981 als Geschenk von Todor Zhivkov an seine Tochter. Das gigantische Kongresszentrum mit 14 Sälen ist heute Veranstaltungsort für Konzerte, Messen und das Sofia Film Festival. Startpunkt des Vitosha Boulevards.",
    "entry_fee": "Außen kostenlos · Veranstaltungen variieren",
    "visit_duration": "15 Min (Außen)",
    "best_time_to_visit": "Abends, der Platz davor ist belebt",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Sozialistischer Brutalismus 1981\", \"Größtes Kongresszentrum Südosteuropas\", \"Startpunkt Vitosha Blvd\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Je nach Veranstaltung"
  },
  {
    "category_id": 4,
    "name": "National History Museum",
    "meta": "Boyana · goldene Schätze · 15 Min vom Zentrum",
    "rating": null,
    "price_range": null,
    "lat": 42.6550407,
    "lng": 23.2708231,
    "description": "Das größte Museum Bulgariens liegt im Vorort Boyana in einer ehemaligen kommunistischen Staatsresidenz — 15 Min vom Zentrum per Taxi (ca. 8 BGN). Über 650.000 Exponate: thrakische Goldschätze, mittelalterliche Ikonen und osmanische Artefakte. Nur bei echtem Museumsinteresse lohnenswert.",
    "entry_fee": "10 BGN",
    "visit_duration": "2–3 Std",
    "best_time_to_visit": "Wochentags (weniger voll)",
    "photo_allowed": "Eingeschränkt (kein Blitz)",
    "guided_tours": "Ja, gegen Aufpreis",
    "key_features": "[\"Thrakischer Panagyurishte-Goldschatz\", \"650.000+ Exponate\", \"Ehemalige Staatsresidenz Zhivkovs\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "tägl. 9:30–18:00 (Nov–Mrz bis 17:30)"
  },
  {
    "category_id": 4,
    "name": "Borisova Gradina Park",
    "meta": "Größter Stadtpark · Spazieren, Joggen, Picknick",
    "rating": null,
    "price_range": null,
    "lat": 42.6840072,
    "lng": 23.3399402,
    "description": "Sofias größter Park (340 ha) wurde 1884 angelegt und ist das grüne Herz der Stadt. Neben Spazierwegen, Rosengarten und Spielplätzen gibt es mehrere Cafés und das Vasil-Levski-Stadion. Im Mai ideal für einen entspannten Nachmittag mit Picknick und etwas Abstand vom Touristenstress.",
    "entry_fee": "Kostenlos",
    "visit_duration": "1–2 Std",
    "best_time_to_visit": "Nachmittags im Mai",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"340 Hektar Stadtpark\", \"Rosengarten\", \"Cafés und Restaurants im Park\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Immer geöffnet"
  },
  {
    "category_id": 4,
    "name": "National Archaeological Museum",
    "meta": "Römische & thrakische Artefakte · neben Präsidentenpalast",
    "rating": null,
    "price_range": null,
    "lat": 42.6963979,
    "lng": 23.3245781,
    "description": "Untergebracht in der ehemaligen großen Moschee Sofias aus dem 15. Jahrhundert zeigt das Nationalmuseum die reichste archäologische Sammlung Bulgariens. Highlights sind thrakische Gold- und Silberschätze sowie antike Skulpturen. Sehr gutes Preis-Leistungs-Verhältnis und zentral gelegen.",
    "entry_fee": "10 BGN",
    "visit_duration": "1–1,5 Std",
    "best_time_to_visit": "Wochentags morgens",
    "photo_allowed": "Erlaubt (kein Blitz)",
    "guided_tours": "Ja, gegen Aufpreis",
    "key_features": "[\"Im Bau der Bujuk-Camii-Moschee (1474)\", \"Thrakische Goldschätze\", \"Direkt neben dem Präsidentenpalast\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Di–So 10:00–18:00, Mo geschlossen"
  },
  {
    "category_id": 4,
    "name": "National Art Gallery",
    "meta": "Bulgarische Kunst · im ehemaligen Königspalast",
    "rating": null,
    "price_range": null,
    "lat": 42.6965175,
    "lng": 23.3267637,
    "description": "Im ehemaligen Königspalast aus dem 19. Jahrhundert zeigt die Nationalgalerie die wichtigste Sammlung bulgarischer Kunst vom Mittelalter bis heute. Der Palast selbst ist sehenswert — hohe Decken, Parkett und Säle wie aus einer anderen Epoche. Ruhig und wenig überlaufen.",
    "entry_fee": "6 BGN",
    "visit_duration": "1–1,5 Std",
    "best_time_to_visit": "Wochentags",
    "photo_allowed": "Eingeschränkt",
    "guided_tours": "Keine",
    "key_features": "[\"Ehemaliger Königspalast 19. Jh.\", \"Bulgarische Kunst vom Mittelalter bis heute\", \"Prächtige historische Säle\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Di–So 10:00–18:00, Mo geschlossen"
  },
  {
    "category_id": 4,
    "name": "Monument to the Tsar Liberator",
    "meta": "Reiterstandbild · russisch-türkischer Krieg",
    "rating": null,
    "price_range": null,
    "lat": 42.6937430,
    "lng": 23.3323179,
    "description": "Das 1907 eingeweihte Reiterstandbild zeigt Zar Alexander II. von Russland, der Bulgarien 1878 nach fast 500 Jahren von osmanischer Herrschaft befreite. Es steht prominent gegenüber dem Nationaltheater, zwischen National Art Gallery und Nationalversammlung.",
    "entry_fee": "Kostenlos",
    "visit_duration": "5 Min",
    "best_time_to_visit": "Tagsüber",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Zar Alexander II. zu Pferd\", \"Symbol der Befreiung 1878\", \"Zwischen Nationaltheater und Parlament\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Immer zugänglich"
  },
  {
    "category_id": 4,
    "name": "Boyana Church",
    "meta": "UNESCO-Welterbe · 13. Jh. Fresken · 15 Min vom Zentrum",
    "rating": null,
    "price_range": null,
    "lat": 42.6446240,
    "lng": 23.2661946,
    "description": "UNESCO-Welterbe und eines der bedeutendsten mittelalterlichen Kunstdenkmäler Europas. Die Fresken von 1259 zeigen realistische menschliche Gesichter — fast 200 Jahre vor der Florentiner Renaissance. Täglich nur begrenzte Gruppen erlaubt: Ticket unbedingt im Voraus kaufen!",
    "entry_fee": "10 BGN · Online-Reservierung empfohlen",
    "visit_duration": "45 Min–1 Std",
    "best_time_to_visit": "Morgens (weniger voll), Taxi ~8 BGN vom Zentrum",
    "photo_allowed": "Verboten (Freskenschutz)",
    "guided_tours": "Im Ticket enthalten",
    "key_features": "[\"UNESCO-Welterbe\", \"Fresken von 1259 (vor der Renaissance)\", \"Sehr begrenzte Besucherzahl — Ticket im Voraus!\"]",
    "dress_code": "Schultern bedeckt",
    "service_times": "tägl. 9:30–17:30 (Okt–Apr bis 17:00)"
  },
  {
    "category_id": 4,
    "name": "Doctors' Garden",
    "meta": "Historischer Park · nahe Universität · Sitzbänke",
    "rating": null,
    "price_range": null,
    "lat": 42.6944947,
    "lng": 23.3384863,
    "description": "Der historische Park aus dem 19. Jahrhundert wurde zum Gedenken an die Ärzte und Sanitäter des Russisch-Türkischen Befreiungskriegs angelegt. Ruhiger und weniger touristisch als der Crystal Garden — ideal für eine kurze Pause zwischen den Sehenswürdigkeiten in der Universitätsnähe.",
    "entry_fee": "Kostenlos",
    "visit_duration": "15–20 Min",
    "best_time_to_visit": "Tagsüber",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Denkmal für Kriegsärzte 1877/78\", \"Ruhige Oase nahe der Universität\", \"Historischer Park 19. Jh.\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Immer geöffnet"
  },
  {
    "category_id": 8,
    "name": "Vasil Levski National Stadium",
    "meta": "Nationalstadion · 44.000 Plätze · Konzerte & Fußball",
    "rating": null,
    "price_range": null,
    "lat": 42.6861116,
    "lng": 23.3324048
  },
  {
    "category_id": 4,
    "name": "Sedmochislenitsi Church (Seven Saints)",
    "meta": "Östlich-orthodoxe Kirche · byzantinische Architektur",
    "rating": null,
    "price_range": null,
    "lat": 42.6899482,
    "lng": 23.3276210,
    "description": "Die Kirche der Sieben Heiligen aus dem 16. Jahrhundert war ursprünglich eine osmanische Moschee und wurde nach der Befreiung 1878 zur orthodoxen Kirche umgewandelt. Bekannt für ihre stimmungsvollen Wandmalereien, liegt sie etwas abseits der Touristenrouten im Studentenviertel.",
    "entry_fee": "Kostenlos",
    "visit_duration": "15 Min",
    "best_time_to_visit": "Morgens",
    "photo_allowed": "Eingeschränkt",
    "guided_tours": "Keine",
    "key_features": "[\"Ursprünglich osmanische Moschee (16. Jh.)\", \"Wandmalereien 19. Jh.\", \"Abseits der Touristenrouten\"]",
    "dress_code": "Schultern bedeckt",
    "service_times": "tägl. 7:00–18:00"
  },
  {
    "category_id": 4,
    "name": "City Garden",
    "meta": "Kleiner Park · zwischen Präsidentenpalast & Nationaltheater",
    "rating": null,
    "price_range": null,
    "lat": 42.6952028,
    "lng": 23.3254876,
    "description": "Der elegante Stadtgarten zwischen dem Nationaltheater und dem Präsidentenpalast ist Sofias intimstes Grünstück — ein schöner Brunnen, Bänke unter Bäumen und abends das goldene Glühen des Theaters als Kulisse. Perfekter Ort für eine kurze Pause mitten in der Stadt.",
    "entry_fee": "Kostenlos",
    "visit_duration": "15 Min",
    "best_time_to_visit": "Abends (Theaterbeleuchtung)",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Zentralste Grünoase Sofias\", \"Blick auf das beleuchtete Nationaltheater\", \"Eleganter Brunnen\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Immer geöffnet"
  },
  {
    "category_id": 4,
    "name": "National Museum of Natural History",
    "meta": "Naturkunde · Mineralien · prähistorische Fossilien",
    "rating": null,
    "price_range": null,
    "lat": 42.6959958,
    "lng": 23.3285616,
    "description": "Das älteste Naturkundemuseum Bulgariens (gegründet 1889) zeigt eine beeindruckende Mineraliensammlung, prähistorische Fossilien und zoologische Exponate. Ein ausgestopfter Wal hängt von der Decke. Gut für einen Regentag oder wenn jemand in der Gruppe Naturwissenschaften mag.",
    "entry_fee": "5 BGN",
    "visit_duration": "1–1,5 Std",
    "best_time_to_visit": "Bei schlechtem Wetter",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Gegründet 1889\", \"Umfangreiche Mineraliensammlung\", \"Wal-Exponat\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "tägl. 10:00–18:00"
  },
  {
    "category_id": 4,
    "name": "Museum of Socialist Art",
    "meta": "Kommunistische Ära · Skulpturen & Propaganda",
    "rating": null,
    "price_range": null,
    "lat": 42.6657537,
    "lng": 23.3581933,
    "description": "Einzigartiges Freilichtmuseum am östlichen Stadtrand mit Statuen aus der kommunistischen Ära — darunter ein riesiges Lenin-Denkmal. Dazu eine permanente Ausstellung über den Sozialismus in Bulgarien (1944–1989). Kurios, gruselig, lehrreich — absolut sehenswert für alle, die Geschichte mögen.",
    "entry_fee": "6 BGN",
    "visit_duration": "1–1,5 Std",
    "best_time_to_visit": "Tagsüber (Freilichtbereich)",
    "photo_allowed": "Erlaubt",
    "guided_tours": "Keine",
    "key_features": "[\"Freilicht-Skulpturenpark mit Lenin & Co.\", \"Ausstellung Kommunismus 1944–1989\", \"Ca. 20 Min vom Zentrum (Taxi ~10 BGN)\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Di–So 10:00–17:30, Mo geschlossen"
  },
  {
    "category_id": 4,
    "name": "National Gallery for Foreign Art",
    "meta": "Internationale Kunst · asiatisch, afrikanisch, europäisch",
    "rating": null,
    "price_range": null,
    "lat": 42.6962016,
    "lng": 23.3341805,
    "description": "In einem neoklassizistischen Gebäude neben dem Nationaltheater zeigt die Galerie Werke aus Asien, Afrika und Europa — indische Skulpturen, japanische Holzschnitte, afrikanische Masken und europäische Gemälde. Überraschend vielfältig, wenig überlaufen und zentral gelegen.",
    "entry_fee": "6 BGN",
    "visit_duration": "1 Std",
    "best_time_to_visit": "Wochentags",
    "photo_allowed": "Eingeschränkt",
    "guided_tours": "Keine",
    "key_features": "[\"Asiatische, afrikanische & europäische Kunst\", \"Ruhig und wenig überlaufen\", \"Direkt neben dem Nationaltheater\"]",
    "dress_code": "Kein Dresscode",
    "service_times": "Mi–Mo 11:00–18:00, Di geschlossen"
  },
  {
    "category_id": 2,
    "name": "Cosmos",
    "meta": "Bulg. Fusion, Fine Dining",
    "rating": 4.6,
    "price_range": "€€€",
    "lat": 42.6947558,
    "lng": 23.3190422,
    "website_url": "https://cosmosbg.com",
    "address": "ul. Lavele 19, 1000 Sofia",
    "opening_hours": "Mon-Fri 12:00-15:30, 17:30-22:30; Sat-Sun 11:00-16:00, 18:00-22:30",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 888 200 700",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager\", \"price\": \"6 BGN / 0.33L\"}, {\"name\": \"Heineken\", \"style\": \"Lager\", \"price\": \"6 BGN / 0.33L\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"9-Gang-Degustationsmenü\", \"note\": \"Signature\"}, {\"name\": \"Kachamak (Ziegenkäse, Pilze, Schmand)\"}, {\"name\": \"Moussaka mit Kalb & Aubergine\"}, {\"name\": \"Lamm Gergiov\"}, {\"name\": \"Gebratene Paprika mit Kroketten & Pinienkernen\"}, {\"name\": \"Bulgarian Rose Dessert\"}]",
    "local_specialties": null,
    "music_type": "Ruhig, Fine Dining",
    "crowd_type": "Foodies, Fine Dining, Date Night",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Reservierung Pflicht. 9-Gang-Menü ist die Paradedisziplin. Zero-Waste-Philosophie, Zutaten von kleinen bulg. Bauern. Mittags & abends mit Pause dazwischen.",
    "fun_facts": "\"Traditional Space Cuisine\" — bulg. Zutaten kosmisch reinterpretiert, Planeten- & Sternendeko. Seit 01/2024 Mitglied der Jeunes Restaurateurs (JRE). Mehrfacher Bakhus- & GoGuide-Award-Gewinner."
  },
  {
    "category_id": 2,
    "name": "Supa Star",
    "meta": "Suppen · Lunch-Geheimtipp",
    "rating": 4.6,
    "price_range": "€",
    "lat": 42.6926533,
    "lng": 23.3311016,
    "website_url": "https://www.facebook.com/BarSupaStar",
    "address": "ul. Tsar Ivan Shishman 8, 1000 Sofia",
    "opening_hours": "Mon-Fri 10:30-21:00, Sat 12:00-21:00, Sun 12:00-19:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 2 468 9065",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager\", \"price\": \"3 BGN / 0.5L\"}, {\"name\": \"Fritz Kola\", \"price\": \"4 BGN\", \"note\": \"kein Bier, aber beliebt\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"6 rotierende Suppen täglich\", \"note\": \"wechseln\"}, {\"name\": \"Marokkanische Kichererbsensuppe\"}, {\"name\": \"Chili con Carne Suppe\"}, {\"name\": \"Süßkartoffel-Cremesuppe\"}, {\"name\": \"Sandwiches\", \"note\": \"auch vegan/vegetarisch\"}, {\"name\": \"Salate & Desserts\"}]",
    "local_specialties": null,
    "music_type": "Locker, Café-Vibe",
    "crowd_type": "Lunch-Crowd, Locals, Büro-Menschen",
    "seating_options": "[\"indoor\", \"takeaway\"]",
    "pro_tips": "Perfekt für schnellen Lunch oder Katerfrühstück. Suppen gibt's to-go. 6 Sorten rotieren täglich — wer Glück hat, erwischt Bob Chorba (bulg. Bohnensuppe).",
    "fun_facts": "Erste Suppenbar Bulgariens — eröffnet 2009. Pionier der Sofia-To-Go-Szene."
  },
  {
    "category_id": 2,
    "name": "Hadjidraganov's Houses",
    "meta": "Traditionell, Live-Musik",
    "rating": 4.5,
    "price_range": "€€",
    "lat": 42.7065851,
    "lng": 23.3226108,
    "website_url": "https://kashtite.com",
    "address": "ul. Kozloduy 75, Sofia (Ecke Maria Luiza Blvd)",
    "opening_hours": "Mon-Sun 11:30-23:30",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Ariana\", \"style\": \"Sofias Lokalbrauerei\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Hausrakia\", \"style\": \"Pflaume oder Traube\", \"price\": \"3 BGN / Schuss\", \"note\": \"Zum Essen immer bestellen!\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Ganzes Huhn im Ton-Ei\", \"note\": \"Signature\"}, {\"name\": \"Porcini-Suppe im Brotlaib\"}, {\"name\": \"Voevodska Sofra\", \"note\": \"Gelage-Platte für 10 Personen\"}, {\"name\": \"Lamm-, Kalb-, Wildgerichte\"}, {\"name\": \"Bulgarische Weine & Rakia\", \"note\": \"riesige Auswahl\"}]",
    "local_specialties": null,
    "music_type": "Live Folk Music tgl. außer Di, 20:00-23:00",
    "crowd_type": "Touristen, Gruppen, Traditionsliebhaber",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Reservierung empfohlen — gerade für Gruppen. Voevodska Sofra bestellen, wenn ihr zu 10 seid. Live-Musik täglich außer Dienstag.",
    "fun_facts": "Vier restaurierte Häuser aus dem 19. Jh. — jedes in einem anderen Bulgarien-Baustil (Bansko, Melnik, Zheravna, Koprivshtitsa). Architekturmuseum mit Küche."
  },
  {
    "category_id": 2,
    "name": "Shtastlivetsa",
    "meta": "Klassiker am Vitosha Blvd",
    "rating": 4.5,
    "price_range": "€€",
    "lat": 42.6933136,
    "lng": 23.3205572,
    "website_url": "https://www.shtastliveca.com",
    "address": "bul. Vitosha 27, 1000 Sofia",
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 2 4411 155",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Ariana\", \"style\": \"Lager Flasche\", \"price\": \"4 BGN / 0.5L\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Banitsa (Blätterteig mit Käse)\"}, {\"name\": \"Kebapche (Hackfleisch-Würstchen)\"}, {\"name\": \"Shopska Salata\"}, {\"name\": \"Herzhafte bulg. Eintöpfe\"}, {\"name\": \"Grillfleisch\"}, {\"name\": \"Vegetarische Optionen\"}]",
    "local_specialties": null,
    "music_type": "Ruhig, manchmal Themen-Abende",
    "crowd_type": "Mixed — Touristen, Locals, Business-Lunch",
    "seating_options": "[\"indoor\", \"garden\"]",
    "pro_tips": "Reservierung ratsam — sehr beliebt am Vitosha Blvd. Lunch-Specials günstiger. Sommergarten hat 80+ Plätze.",
    "fun_facts": "\"Shtastlivetsa\" = der Glückliche. Shabby-chic- & Vintage-Interior im Stil der 1930er. Themen-Nights zu wechselnden Küchen der Welt."
  },
  {
    "category_id": 2,
    "name": "Pastorant",
    "meta": "Italienisch, intim · So zu",
    "rating": 4.5,
    "price_range": "€€",
    "lat": 42.6933313,
    "lng": 23.318984,
    "website_url": null,
    "address": "ul. Tsar Asen 16, 1000 Sofia",
    "opening_hours": "Mon-Sat 12:00-22:30, Sun geschlossen",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 702 6190",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager Flasche\", \"price\": \"4 BGN / 0.33L\"}, {\"name\": \"Moretti\", \"style\": \"Italienisches Lager\", \"price\": \"5 BGN / 0.33L\", \"note\": \"passt zum Konzept\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Al-dente Pasta (wechselnd)\"}, {\"name\": \"Holzofen-Pizza\"}, {\"name\": \"Antipasti\"}, {\"name\": \"Salate\"}, {\"name\": \"Desserts\"}, {\"name\": \"Weinliste\", \"note\": \"bulgarisch & italienisch, kuratiert\"}]",
    "local_specialties": null,
    "music_type": "Leise, intim",
    "crowd_type": "Couples, Date Night, Italophile",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Kleine, fokussierte Karte — kein \"alles für alle\", sondern alles gut. Reservierung empfohlen. Sonntag zu, also Timing beachten.",
    "fun_facts": "Kurze, präzise Speisekarte — für Bulgarien ungewöhnlich, aber genau das Konzept: Pasta al dente wird hier ernst genommen."
  },
  {
    "category_id": 2,
    "name": "Checkpoint Charly",
    "meta": "Berlin-Vibes · bulg. Küche",
    "rating": 4.4,
    "price_range": "€€",
    "lat": 42.6928486,
    "lng": 23.3277671,
    "website_url": "http://www.checkpointcharlybg.com",
    "address": "ul. Ivan Vazov 12, 1000 Sofia",
    "opening_hours": "Mon-Sun 11:30-23:30",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 2 988 0370",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Paulaner\", \"style\": \"Hefeweizen\", \"price\": \"7 BGN / 0.5L\", \"note\": \"passend zu den Berlin-Vibes\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Moderne bulgarische Küche\"}, {\"name\": \"Schnitzel & Schweinefleisch-Specials\"}, {\"name\": \"Internationale Gerichte\"}, {\"name\": \"Lunch-Special\", \"note\": \"mittags günstiger\"}, {\"name\": \"Weinauswahl\"}]",
    "local_specialties": null,
    "music_type": "Live Jazz mehrmals pro Woche",
    "crowd_type": "Locals, Touristen, Business-Lunch, Jazz-Fans",
    "seating_options": "[\"indoor\", \"garden\"]",
    "pro_tips": "Einziges Live-Jazz-Restaurant in Sofia — Spieltage vorher checken. Sommergarten (plus noch einer zwei Häuser weiter). Mittags-Lunch-Special.",
    "fun_facts": "Deko mit Kopien der Schilder vom historischen Checkpoint Charlie in Berlin. Seit 10+ Jahren feste Größe in Sofias Zentrum. Atmosphäre: Jazzclub-Feeling der 1980er."
  },
  {
    "category_id": 2,
    "name": "Manastirska Magernitsa",
    "meta": "Klosterküche · 200+ Gerichte",
    "rating": 4.3,
    "price_range": "€€",
    "lat": 42.6893428,
    "lng": 23.3246,
    "website_url": "https://magernitsa.com",
    "address": "ul. Khan Asparuh 67, 1000 Sofia",
    "opening_hours": "Mon-Sun 12:00-23:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 89 994 9400",
    "beer_menu": "[{\"name\": \"Ariana\", \"style\": \"Sofias Lokalbrauerei, Lager\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Hausrakia\", \"style\": \"bulgarische Tradition\", \"price\": \"3 BGN / Schuss\", \"note\": \"Pflicht zum Essen!\"}, {\"name\": \"Himbeerwein\", \"style\": \"Spezialität des Hauses\", \"price\": \"5 BGN / Glas\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Schweinenacken\"}, {\"name\": \"Hähnchen auf Ofenkartoffeln\"}, {\"name\": \"Wildschwein-Eintopf\"}, {\"name\": \"Hirsch-Eintopf\"}, {\"name\": \"Kalbs-Chomlek\"}, {\"name\": \"Weiße Bohnen (vegetarisch)\"}, {\"name\": \"Butter-Pilze (vegetarisch)\"}, {\"name\": \"200+ Gerichte auf der Karte\"}]",
    "local_specialties": null,
    "music_type": "Live bulgarische Traditionsmusik (im Sommergarten)",
    "crowd_type": "Touristen, Traditionsliebhaber, Foodies",
    "seating_options": "[\"indoor\", \"garden\"]",
    "pro_tips": "Die Karte ist buchdick — plant Zeit zum Stöbern ein. Im Sommer unbedingt in den Garten mit Live-Musik. Für Gruppen: Wildgerichte teilen.",
    "fun_facts": "\"Magernitsa\" = der Raum im Kloster, in dem die Mönche kochen und essen. Jedes Rezept stammt von einem anderen bulg. Kloster. Haus gehörte einst Prof. Krastyo Krastev, dem ersten bulg. Literaturkritiker nach der Befreiung. Seit 2002 in Betrieb."
  },
  {
    "category_id": 2,
    "name": "Dark Sister by Made in Home",
    "meta": "Modern, feurig · Angel Kanchev",
    "rating": 4.3,
    "price_range": "€€",
    "lat": 42.6898,
    "lng": 23.324,
    "website_url": "https://darksister.bg",
    "address": "ul. Angel Kanchev 30A, 1000 Sofia",
    "opening_hours": "Mon 14:00-23:00, Tue-Sun 12:00-23:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 87 688 4014",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Craft Beer (rotierend)\", \"style\": \"IPA oder Pale Ale\", \"price\": \"7–9 BGN / 0.33L\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Gegrilltes Saisongemüse & Fleisch\", \"note\": \"alles über Feuer gegart\"}, {\"name\": \"Three Types of Hummus Plate\"}, {\"name\": \"Kebab Platter\", \"note\": \"Signature\"}, {\"name\": \"Chicken Fajita\"}, {\"name\": \"Saisonale Tagesgerichte\"}, {\"name\": \"Bulgarische & internationale Weine\"}]",
    "local_specialties": null,
    "music_type": "Modern, entspannt",
    "crowd_type": "Locals, Kreative, Date Night",
    "seating_options": "[\"indoor\", \"outdoor\"]",
    "pro_tips": "Karte ändert sich saisonal — immer nach der Tagesempfehlung fragen. Alles über Feuer gegart: authentisches Kochkonzept. Reservierung am Wochenende empfohlen.",
    "fun_facts": "Früher 'Made in Home' (Sofias Kult-Bruncher), 2023 zu 'Dark Sister' umgebaut — artsy, mit Feuer-Küche und Retro-Modern-Vibe. Unverarbeitete Saisonprodukte als Grundprinzip."
  },
  {
    "category_id": 2,
    "name": "Moma Bulgarian Food",
    "meta": "Bulg. Küche & Wein",
    "rating": 4.2,
    "price_range": "€€",
    "lat": 42.692,
    "lng": 23.3178,
    "website_url": "https://moma-restaurant.com",
    "address": "ul. Solunska 28, 1000 Sofia",
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 562 2020",
    "beer_menu": "[{\"name\": \"Ariana\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Patatnik\", \"note\": \"traditionelle Kartoffel-Spezialität aus den Rhodopen\"}, {\"name\": \"Salate im Brotlaib\", \"note\": \"knusprig serviert\"}, {\"name\": \"Moderne Re-Interpretationen bulgarischer Klassiker\"}, {\"name\": \"Mavrud\", \"note\": \"bulg. Rotwein, vollmundig\"}, {\"name\": \"Melnik\", \"note\": \"bulg. Rotwein, trocken\"}]",
    "local_specialties": null,
    "music_type": "Ruhig, Fokus auf Essen & Wein",
    "crowd_type": "Touristen, Foodies, Date Night",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Reservierung essentiell — vor allem am Wochenende. Lunch ist ruhiger. Weinkarte ernst nehmen und nach bulgarischen Sorten fragen.",
    "fun_facts": "3 Stockwerke, 9 Essenssäle — jeder mit eigener Gestaltung rund um bulg. Mädchen-/Frauen-Traditionen (\"Moma\" = junge Frau). Umfangreiche Weinkarte mit heimischen Sorten wie Mavrud & Melnik."
  },
  {
    "category_id": 2,
    "name": "Divaka",
    "meta": "Groß, laut, traditionell",
    "rating": 4.1,
    "price_range": "€€",
    "lat": 42.6892888,
    "lng": 23.3253657,
    "website_url": "https://www.facebook.com/restaurants.and.pubs.divaka",
    "address": "ul. 6-ti Septemvri 41А, 1000 Sofia",
    "opening_hours": "Mon-Sun 10:00-02:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Divaka-Rakia\", \"style\": \"Hausrakia\", \"price\": \"3 BGN / Schuss\", \"note\": \"Empfehlung: zum Essen immer mit Salat\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Shopska Salata\", \"note\": \"Klassiker\"}, {\"name\": \"Meshana Skara\", \"note\": \"Gemischte Grillplatte\"}, {\"name\": \"Ovcharska Salata\"}, {\"name\": \"Tarator\", \"note\": \"kalte Joghurt-Gurken-Suppe\"}, {\"name\": \"Grillfleisch (Kebapche, Kyufte)\"}, {\"name\": \"Nur 4-seitige Karte\", \"note\": \"für bulg. Verhältnisse ungewöhnlich kurz\"}]",
    "local_specialties": null,
    "music_type": "Keine Live-Musik, laut & lebhaft (drinnen)",
    "crowd_type": "Locals, Studenten, Gruppen",
    "seating_options": "[\"indoor\", \"summer garden\", \"winter garden\"]",
    "pro_tips": "Drinnen wird's bei vollem Haus laut (Akustik-Katastrophe). Lieber in den Garten. Bis 2 Uhr offen — perfekt nach spätem Bier. 3 Filialen in Sofia.",
    "fun_facts": "\"Divaka\" = die Wilde / der Wilde. Bei bulgarischen Riesenkarten eine Ausnahme: nur 4 Seiten. Günstig, traditionell, immer voll."
  },
  {
    "category_id": 2,
    "name": "Skapto Burgers & Beer",
    "meta": "Handgemachte Burger",
    "rating": 4.4,
    "price_range": "€€",
    "lat": 42.695,
    "lng": 23.332,
    "website_url": "https://www.instagram.com/skapto/",
    "address": "ul. Tsar Shishman 20, 1000 Sofia",
    "opening_hours": "Mo-Mi 11:30-22:00, Do-So 11:30-23:30",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 700 11313",
    "beer_menu": "[{\"name\": \"No Use For A Cooler Name\", \"style\": \"Haus-Pale Ale (Skapto Eigenbrau)\", \"price\": \"7 BGN / 0.33L\", \"note\": \"Das Signature — unbedingt probieren!\"}, {\"name\": \"Craft Biere (rotierend)\", \"price\": \"7–9 BGN / 0.33L\", \"note\": \"Kleine Auswahl passend zu den Burgern — nach Tagesempfehlung fragen\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Handgemachte Beef-Burger\", \"note\": \"Signature\"}, {\"name\": \"Vegetarische Burger-Varianten\"}, {\"name\": \"Hand-cut Fries\"}, {\"name\": \"Saisonale Specials\"}]",
    "local_specialties": null,
    "music_type": "Casual, leise Hintergrundmusik",
    "crowd_type": "Locals, Expats, Amerikan.-Uni-Absolventen, Burger-Fans",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Die Craft Beer Auswahl wird passend zu den Burger-Rezepten kuratiert — fragt nach der Empfehlung. 3 Standorte in Sofia (Tsar Shishman, Iskar, San Stefano).",
    "fun_facts": "2013 von Alumni der American University in Bulgaria gegründet — als Hangout-Spot für Ex-Studenten. Gewann 2016 den \"King of Burgers\"-Titel. Alle 3 Filialen in Sofias Top-3-Burger auf Tripadvisor."
  },
  {
    "category_id": 2,
    "name": "Sun Moon",
    "meta": "Vegetarisch / vegan",
    "rating": 4.4,
    "price_range": "€€",
    "lat": 42.6862516,
    "lng": 23.3157325,
    "website_url": "https://www.happycow.net/reviews/sunmoon-sofia-34259",
    "address": "ul. 6-ti Septemvri 39 / ul. Shandor Petofi 55, 1000 Sofia",
    "opening_hours": "Mon-Sat 08:30-22:00, Sun 08:30-21:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 89 913 8411",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Vegane Biere auf Anfrage\", \"note\": \"kleines Sortiment\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Bob Chorba\", \"note\": \"bulg. Bohnensuppe\"}, {\"name\": \"Lentil Banitsa\", \"note\": \"vegane Version des Klassikers\"}, {\"name\": \"Lutenica & Kyopoolu\", \"note\": \"bulg. Aufstriche\"}, {\"name\": \"Mish-Mash\", \"note\": \"bulg. Paprika-Rührei, hier vegan\"}, {\"name\": \"Parsley Pesto\"}, {\"name\": \"Bean Stew\"}, {\"name\": \"Eigene Bäckerei\", \"note\": \"frische Backwaren\"}]",
    "local_specialties": null,
    "music_type": "Ruhiger Café-Vibe",
    "crowd_type": "Vegans, Vegetarians, Health-Conscious, Locals",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Abends voll — Reservierung empfohlen. Bulg. Section auf der Karte probieren: traditionelle Gerichte ohne Tierprodukte. Essen für 2 mit 3 Gängen und Drinks ca. 53 Lev (~27€).",
    "fun_facts": "Einer der ersten 100% vegetarisch/vegan Läden Sofias. Mittlerweile Institution. Bulg. Rezepte werden hier systematisch ent-tierlicht — Bob Chorba & Banitsa gehen auch ohne Speck & Feta."
  },
  {
    "category_id": 2,
    "name": "Izbata Tavern",
    "meta": "Mehana · Herzstück-Küche · 20+ Jahre",
    "rating": 4.3,
    "price_range": "€€",
    "lat": 42.692531,
    "lng": 23.329754,
    "website_url": "https://tavern.izbata.bg/en/",
    "address": "ul. Slavyanska 18, 1000 Sofia",
    "opening_hours": "Mon-Sun 11:00-23:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 2 989 5533",
    "beer_menu": "[{\"name\": \"Ariana\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager Flasche\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Hausrakia\", \"price\": \"3 BGN / Schuss\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Shopska Salata\", \"note\": \"mit frischem Sirene-Käse\"}, {\"name\": \"Kavarma\", \"note\": \"langsam gegart im Tontopf\"}, {\"name\": \"Kebapche\", \"note\": \"handgeformt, über offenem Feuer gegrillt\"}, {\"name\": \"Banitsa\", \"note\": \"frisch aus dem Ofen\"}, {\"name\": \"Hähnchen-Kavarma\"}, {\"name\": \"Musaka\"}, {\"name\": \"Tarator\", \"note\": \"kalte Joghurt-Gurkensuppe\"}, {\"name\": \"Lammgerichte\"}]",
    "local_specialties": null,
    "music_type": "Live-Folklore abends",
    "crowd_type": "Touristen, Locals, Gruppen",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Reservierung empfohlen — sehr beliebt. Live-Folklore-Musik am Abend. Zweite Filiale (Izbata Tavern 2) 10 Min entfernt, falls voll. Nah am Alexander-Newski-Platz.",
    "fun_facts": "Seit über 20 Jahren geöffnet — Rezepte aus allen Regionen Bulgariens gesammelt. Mehrfach ausgezeichnet für Qualität und Stil. In Gehweite von Kathedrale, Parlament und Nationaltheater."
  },
  {
    "category_id": 2,
    "name": "Staria Chinar",
    "meta": "Mehana · Holzofen · kein Tourist · Insider",
    "rating": 4.6,
    "price_range": "€€",
    "lat": 42.699151,
    "lng": 23.336668,
    "website_url": "https://dineout.bg/en/restaurants/staria-chinar-1",
    "address": "bul. Knyaz Alexander Dondukov 71, 1527 Sofia",
    "opening_hours": "Mon-Sun 11:00-23:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 887 455 050",
    "beer_menu": "[{\"name\": \"Pirinsko\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\", \"note\": \"Klassiker in bulgarischen Mehanas\"}, {\"name\": \"Kamenitza\", \"style\": \"Lager Flasche\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Hausrakia\", \"style\": \"Pflaume\", \"price\": \"3 BGN / Schuss\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Pork Knuckle aus dem Holzofen\", \"note\": \"Signature\"}, {\"name\": \"Lamm nach St.-Georgs-Rezept\"}, {\"name\": \"Wildgerichte\", \"note\": \"saisonal\"}, {\"name\": \"Gefüllte Paprika\"}, {\"name\": \"Auberginen-Creme & Lyutenitsa\"}, {\"name\": \"Frischer Fisch\", \"note\": \"wöchentlich wechselnd\"}, {\"name\": \"Bulgarische Appetizer\"}]",
    "local_specialties": null,
    "music_type": "Ruhig, kein Live-Programm",
    "crowd_type": "Einheimische, Kenner — kaum Touristen",
    "seating_options": "[\"indoor\", \"garden\"]",
    "pro_tips": "Reservierung dringend empfohlen — oft ausgebucht. Immer nach Saisonangebot und Fisch fragen. Portionen sehr großzügig — besser zu zweit teilen.",
    "fun_facts": "Das Haus stammt aus dem Jahr 1922 — einer der ältesten Restaurant-Standorte Sofias. 'Staria Chinar' = der Alte Platanbaum. Authentisch ohne Touristenfallen: fast nur Einheimische — gutes Zeichen."
  },
  {
    "category_id": 2,
    "name": "Chevermeto",
    "meta": "Mehana · Lammspieß · Folklore täglich",
    "rating": 4.0,
    "price_range": "€€",
    "lat": 42.683069,
    "lng": 23.316073,
    "website_url": "https://www.chevermeto-bg.com",
    "address": "bul. Pencho Slaveykov 1 (NDK-Bereich), 1463 Sofia",
    "opening_hours": "Mon-Sun 12:00-00:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 563 0308",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Rakia\", \"style\": \"Trauben- oder Pflaumenbrand\", \"price\": \"3 BGN / Schuss\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Cheverme\", \"note\": \"ganzes Lamm täglich am Spieß — Signature\"}, {\"name\": \"Salate & bulgarische Vorspeisen\"}, {\"name\": \"Grillgerichte (Kebapche, Kyufte)\"}, {\"name\": \"Eintöpfe & vegetarische Gerichte\"}]",
    "local_specialties": "[\"Cheverme: ganzes Lamm am Spieß geröstet\"]",
    "music_type": "Folkloreshow täglich: 20:30 Sänger, 21:00 Tanztruppe, 22:00 weitere Sänger",
    "crowd_type": "Touristen, Gruppen, Folklore-Fans",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "3 BGN Aufpreis für das Folkloreprogramm. Lamm am Spieß ist limitiert — früh genug kommen. Ideal für Gruppen und alle, die bulgarische Folklore live erleben wollen.",
    "fun_facts": "'Cheverme' = ganzes Lamm am Spieß — uralte bulgarische Festtradition. In Sofia neben dem NDK täglich mit Livefolklore: Sänger, Tanztruppe und Barbecue am offenen Feuer unter einem Dach."
  },
  {
    "category_id": 2,
    "name": "Vodenitzata",
    "meta": "Mehana · alte Mühle · Vitosha · Folklore + Feuerlauf",
    "rating": 4.2,
    "price_range": "€€",
    "lat": 42.621467,
    "lng": 23.303516,
    "website_url": "https://vodenitzata.com/en/",
    "address": "m. Орехите, kv. Dragalevci, 1415 Sofia (Vitosha, ~20 Min vom Zentrum)",
    "opening_hours": "Mon-Sun 12:00-00:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 2 967 1058",
    "beer_menu": "[{\"name\": \"Ariana\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Hausrakia\", \"style\": \"Hausdestillat, Pflaume\", \"price\": \"4 BGN / Schuss\", \"note\": \"Zum Essen immer mit Salat bestellen!\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Tarator\", \"note\": \"kalte Joghurt-Gurkensuppe — unbedingt starten\"}, {\"name\": \"Kyopoolu\", \"note\": \"Auberginen-Paprika-Aufstrich\"}, {\"name\": \"Bohnensalat\"}, {\"name\": \"Lamm nach St.-Georgs-Rezept\", \"note\": \"Signature\"}, {\"name\": \"Lamm-Chorba\"}, {\"name\": \"Moussaka\"}, {\"name\": \"Gegrilltes Fleisch\"}, {\"name\": \"Hausgemachtes Brot & Lokalkäse\"}, {\"name\": \"Großmutters Kuchen\", \"note\": \"Dessert-Klassiker\"}]",
    "local_specialties": "[\"Rakia & Wein aus Bulgarien\", \"Lammgerichte nach Regionalrezept\"]",
    "music_type": "Folkloreorchester + Tänzer täglich ab 21:00; Nestinari-Feuerlauf-Show",
    "crowd_type": "Touristen, Gruppen, Folklore-Liebhaber",
    "seating_options": "[\"indoor\", \"garden\"]",
    "pro_tips": "Bolt/Taxi ~15-20 Min und ~8€ vom Zentrum. Im Sommer: Garten mit 250 Plätzen am Bach. Im Winter: rustikales Steinhaus mit Kamin. Reservierung für abends unbedingt nötig.",
    "fun_facts": "Restaurierte alte Wassermühle (Vodenitza = Mühle) im Vitosha-Gebirge. 200 Sitzplätze drinnen + 250 im Sommergarten am Fluss. Der Nestinari-Feuerlauf ist UNESCO-geschütztes immaterielles Kulturerbe."
  },
  {
    "category_id": 1,
    "name": "Hambara",
    "meta": "Versteckt, Kerzenlicht · bis 03",
    "rating": 4.3,
    "price_range": null,
    "lat": 42.6901512,
    "lng": 23.3255166,
    "website_url": null,
    "address": "ul. 6-ti Septemvri 22, Sofia",
    "opening_hours": "tgl. ca. 21:00–03:00",
    "payment_methods": "[\"cash\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager\", \"price\": \"4 BGN\"}, {\"name\": \"Craft Beer (rotierend)\", \"price\": \"6–8 BGN\", \"note\": \"kleine Auswahl wechselnder Craft-Biere\"}]",
    "cocktails_menu": null,
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Live Musik, kein fester Spielplan",
    "crowd_type": "Intellektuelles Publikum, Hipster, Locals",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Kein Schild. Kein Licht draußen. Klopf an die Tür und warte. Nur Kerzen drinnen — kein elektrisches Licht. Backyard eines Wohnhauses: kleinen Gang reingehen, Tür am Ende.",
    "fun_facts": "Sofias ältestes Speakeasy aus der Kommunistenzeit: Intellektuelle trafen sich hier im Verborgenen. Kerzen statt Strom — ursprünglich um Behörden zu täuschen. Wer anklopfte, musste früher das Passwort kennen."
  },
  {
    "category_id": 1,
    "name": "Raketa Rakia Bar",
    "meta": "30+ Rakias · Sowjet-Deko",
    "rating": 4.5,
    "price_range": null,
    "lat": 42.698370,
    "lng": 23.342114,
    "website_url": "https://raketarakiabar.bg",
    "address": "bul. Yanko Sakazov 17",
    "opening_hours": "Mon-Fri 11:00-23:00, Sat-Sun 09:00-23:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 2 444 611",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager Flasche\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"170+ Rakia-Sorten\", \"style\": \"Pflaume, Traube, Quitte, Aprikose...\", \"price\": \"2–5 BGN / Schuss\", \"note\": \"Das ist der eigentliche Star hier!\"}]",
    "cocktails_menu": null,
    "food_menu": null,
    "music_type": "Soviet-era memorabilia, Nostalgic",
    "crowd_type": "Locals, Tourists, Golden youth",
    "seating_options": "[\"indoor\", \"terrace\"]",
    "pro_tips": "Rakia workshop - try different types. Extensive list (30+ types of rakia). Terrace shared with Sputnik.",
    "fun_facts": "Named after Soviet rocket, opened 2012. Retro communist-era bar with huge rakia assortment. Full of socialist memorabilia. Historic venue."
  },
  {
    "category_id": 1,
    "name": "Sputnik Cocktail Bar",
    "meta": "Kreativ-Cocktails · neben K2",
    "rating": 4.7,
    "price_range": null,
    "lat": 42.6992,
    "lng": 23.338,
    "website_url": "https://sputnikcocktailbar.com",
    "address": "ul. Yanko Sakuzov 17",
    "opening_hours": "Mon-Sun 12:00-00:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 498 2098",
    "beer_menu": "[{\"name\": \"Heineken\", \"style\": \"Lager vom Fass\", \"price\": \"6 BGN / 250ml · 6.50 BGN / 400ml\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"5.30 BGN / 330ml · 5.90 BGN / 500ml\"}, {\"name\": \"Heineken Silver\", \"style\": \"Lager Flasche\", \"price\": \"6.25 BGN / 330ml\"}, {\"name\": \"Stolichno Weiss\", \"style\": \"Weizenbier Flasche\", \"price\": \"6.45 BGN / 330ml\"}, {\"name\": \"Kein Craft-Fokus\", \"note\": \"Primär Cocktail Bar — Cocktails sind hier das Ziel\"}]",
    "cocktails_menu": "[{\"name\": \"Old Fashioned\", \"price\": \"18–20 BGN\"}, {\"name\": \"Whisky Sour\", \"price\": \"18–20 BGN\"}, {\"name\": \"Signature Cocktails\", \"price\": \"18–25 BGN\", \"note\": \"Saisonal wechselnd, hausgemachte Zutaten\"}]",
    "food_menu": "[{\"name\": \"Finger Food\", \"price\": \"varies\"}, {\"name\": \"Sandwiches\", \"price\": \"varies\"}, {\"name\": \"Salads\", \"price\": \"varies\"}, {\"name\": \"Sweets & Cakes\", \"price\": \"varies\"}]",
    "music_type": "Groovy, Retro, Live DJ",
    "crowd_type": "Trendy, Cocktail enthusiasts",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Average cocktail price $7. Long bar with skilled team. Homemade ingredients. Great coffee during the day.",
    "fun_facts": "Bulgaria's first venue in 50 BEST Discovery. Opened 2023. Long bar with skilled team. Menu adorned with astronaut image. Gold light installation."
  },
  {
    "category_id": 1,
    "name": "Eddie Sicoy Bar",
    "meta": "Guinness vom Hahn · funky",
    "rating": 4.7,
    "price_range": null,
    "lat": 42.689737,
    "lng": 23.3195541,
    "website_url": "https://eddie.sicoy.com",
    "address": "ul. Han Asparuh 37, Sofia",
    "opening_hours": "Mon-Sun 10:00-02:00 (Fri-Sat: 04:00)",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 792 7788",
    "beer_menu": "[{\"name\": \"Guinness\", \"style\": \"Irish Stout vom Fass\", \"price\": \"10 BGN / 0.5L\"}, {\"name\": \"Stella Artois\", \"style\": \"Lager vom Fass\", \"price\": \"8 BGN / 0.5L\"}, {\"name\": \"Burgasko Svetlo\", \"style\": \"Bulgarisches Lager vom Fass\", \"price\": \"6 BGN / 0.5L\"}, {\"name\": \"Craft Biere (rotierend)\", \"style\": \"ca. 10 Sorten\", \"price\": \"8–12 BGN\", \"note\": \"Bier ist stark — aber Whisky & Cocktails sind die echten Stars\"}]",
    "cocktails_menu": null,
    "food_menu": null,
    "music_type": "Live football & music all week round",
    "crowd_type": "Locals, Tourists, Football fans",
    "seating_options": "[\"indoor\", \"outdoor seating\"]",
    "pro_tips": "Great list of cocktails, solid wooden bar, leather sofas. Friendly bartenders (Bobby, Sashko, David).",
    "fun_facts": "Brit/Manhattanesque bar. Open until 4am on weekends. Guinness from tap. Live football & music all week."
  },
  {
    "category_id": 1,
    "name": "Bar Locál",
    "meta": "Kleine Cocktail-Kunstwerke",
    "rating": 4.6,
    "price_range": null,
    "lat": 42.6877404,
    "lng": 23.3248697,
    "website_url": "https://www.barlocalsofia.com",
    "address": "ul. 6-ti Septemvri 38, Sofia",
    "opening_hours": "Mo–Fr 10:00–01:00, Sa 11:00–01:00, So geschlossen",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 884 514 947",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager Flasche\", \"price\": \"5 BGN\"}, {\"name\": \"Craft Beer (rotierend)\", \"price\": \"7–9 BGN\", \"note\": \"Kleine Auswahl — Cocktails sind der eigentliche Fokus\"}]",
    "cocktails_menu": "[{\"name\": \"Signature Cocktails\", \"note\": \"kuratiert, saisonal wechselnd\"}, {\"name\": \"Whisky Selection\"}, {\"name\": \"Gin & Vodka Specials\"}]",
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Lounge, Cocktailbar-Vibe",
    "crowd_type": "Cocktailliebhaber, Locals, Afterwork",
    "seating_options": "[\"indoor\", \"garden\"]",
    "pro_tips": "Im Sommer den versteckten Garten nicht vergessen. Cocktailkarte kuratiert und saisonal. Sonntag geschlossen.",
    "fun_facts": "Whisky-Bar, Cocktailbar, Kaffee und Garten unter einem Dach. Versteckt hinter einer unscheinbaren Fassade auf der 6-ti Septemvri — die Straße ist Sofias inoffizielle Bar-Meile."
  },
  {
    "category_id": 1,
    "name": "Bar Secret Room",
    "meta": "Versteckt · Mi–Sa bis 05",
    "rating": 4.2,
    "price_range": null,
    "lat": 42.6932694,
    "lng": 23.3212068,
    "website_url": "https://secretroom.bg",
    "address": "ul. Hristo Belchev 12, Sofia (Eingang: \"Antique & Bookshop\")",
    "opening_hours": "Mi–Sa 21:00–05:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 87 666 1166",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager\", \"price\": \"5 BGN\"}, {\"name\": \"Fokus liegt auf Cocktails\", \"note\": \"Bier ist Nebensache — Rum & Tequila sind die Stars\"}]",
    "cocktails_menu": "[{\"name\": \"Maßgefertigte Cocktails auf Rum- & Tequila-Basis\", \"note\": \"Größte Rum- & Tequila-Auswahl Bulgariens\"}]",
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Live-Sänger + DJ-Parties",
    "crowd_type": "Party-Crowd, JGA-Gruppen, Eventgäste",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Eingang: unter dem Schild \"Antique & Bookshop\". Tür hinter einem Bücherregal. Manchmal Eintritt je nach Abend. Perfekt für JGAs und Geburtstage.",
    "fun_facts": "Größte Rum- & Tequila-Auswahl ganz Bulgariens. Echter Speakeasy: Eingang hinter einem Bücherregal in einem vermeintlichen Antiquariat."
  },
  {
    "category_id": 1,
    "name": "Caldo Whiskey & Friends",
    "meta": "Riesige Whiskey-Auswahl",
    "rating": 4.6,
    "price_range": null,
    "lat": 42.694,
    "lng": 23.3295,
    "website_url": null,
    "address": "ul. G.S. Rakovski 125, Sofia",
    "opening_hours": "Mo–Do 11:00–02:00, Fr 11:00–04:00, Sa 17:00–04:00, So 17:00–00:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 255 8000",
    "beer_menu": null,
    "cocktails_menu": "[{\"name\": \"Whisky Highball & Classics\", \"note\": \"breite Auswahl auf Whiskybasis\"}]",
    "food_menu": null,
    "local_specialties": "[\"260+ Whiskies aus 20+ Ländern\"]",
    "music_type": "Ruhig, sophisticated",
    "crowd_type": "Whisky-Enthusiasten, Erwachsene, Date Night",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Whisky-Tastings für 2–42 Personen buchbar. 2 Etagen: Erdgeschoss (Geselligkeit & Partys), Obergeschoss (Kamin + Chesterfield-Sessel). Freitag bis 04:00 Uhr.",
    "fun_facts": "260+ Whiskies aus über 20 Ländern — eine der größten Auswahlen Osteuropas. Whisky-Masterclasses mit internationalen Experten buchbar."
  },
  {
    "category_id": 1,
    "name": "Sip'n Bite Wine Spot",
    "meta": "Bulg. Weine · Antipasti",
    "rating": 5,
    "price_range": null,
    "lat": 42.6928,
    "lng": 23.3175,
    "website_url": "https://www.sofiawinespot.com",
    "address": "ul. G.S. Rakovski 145, Sofia (Eingang von Gurko Str.)",
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": null,
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Käse & Charcuterie Flights\", \"note\": \"passend zum Wein\"}, {\"name\": \"Kleine Antipasti\"}]",
    "local_specialties": "[\"Bulgarische Kleinproduzenten-Weine\", \"Weinflights\"]",
    "music_type": "Ruhig, Weinbar-Atmosphäre",
    "crowd_type": "Weinliebhaber, Locals, Foodie-Paare",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Eingang von der Gurko-Straße. Fokus auf kleine unbekannte bulgarische Winzer. Weinflights mit Käse kombinieren.",
    "fun_facts": "Spezialisiert auf bulgarische Kleinerzeuger-Weine — man entdeckt hier Etiketten, die es woanders nicht gibt."
  },
  {
    "category_id": 1,
    "name": "La Cave du Moulin",
    "meta": "Franz. Wein aus Dispenser",
    "rating": 4.8,
    "price_range": null,
    "lat": 42.6927459,
    "lng": 23.3191121,
    "website_url": "https://moulin.bg",
    "address": "ul. Solunska 33, Sofia",
    "opening_hours": "Mo–Sa 10:30–22:00, So 11:00–22:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 255 6554",
    "beer_menu": null,
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Französische Käse\", \"note\": \"wechselnd\"}, {\"name\": \"Charcuterie\"}]",
    "local_specialties": "[\"Weine aus Languedoc, Loire, Bordeaux, Burgund, Elsass, Provence\", \"Wöchentliche Weinverkostungen\"]",
    "music_type": "Ruhig, französischer Charme",
    "crowd_type": "Weinliebhaber, Frankophile, Couples",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Auch Weinladen — Flaschen zum Mitnehmen kaufbar. Wöchentliche Tastings (Termin erfragen). Wein aus dem Dispenser, jederzeit glasweise trinkbar.",
    "fun_facts": "Einzige Bar Sofias mit ausschließlich französischen Weinen. Weinauswahl aus Languedoc, Loire, Bordeaux, Burgund, Elsass, Provence und mehr. Funktioniert als Bar + Weinladen in einem."
  },
  {
    "category_id": 1,
    "name": "Tap Local",
    "meta": "🍺 Craft Beer · 6 Hähne, Top-Qualität",
    "rating": 4.9,
    "price_range": null,
    "lat": 42.6949301,
    "lng": 23.328277,
    "website_url": "https://www.facebook.com/TapLocalTaproom",
    "address": "Sofia Center, ul. Georgi Benkovski 6",
    "opening_hours": "Mon-Fri 14:00-22:00, Sat 13:00-22:00, Sun 13:00-21:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 480 5146",
    "beer_menu": "[{\"name\": \"6–8 rotierende Zapfhähne\", \"note\": \"meist bulgarische Craft-Brauereien\", \"price\": \"6–9 BGN / 0.33L\"}, {\"name\": \"Kazan Artisan\", \"style\": \"Hauptpartner — IPA, Stout, Pale Ale\", \"price\": \"7 BGN / 0.33L\"}, {\"name\": \"Meltum\", \"style\": \"Bulg. Craft-Brauerei\", \"price\": \"7 BGN / 0.33L\"}, {\"name\": \"Cohones Beer\", \"style\": \"Bulg. Craft-Brauerei\", \"price\": \"7 BGN / 0.33L\"}, {\"name\": \"Flaschen & Dosen (rotierend)\", \"price\": \"8–13 BGN\"}]",
    "food_menu": "[{\"name\": \"Bar food menu\", \"price\": \"varies\", \"description\": \"Highly praised by visitors - out of this world!\"}]",
    "music_type": "Metal, Rock",
    "crowd_type": "Locals, Beer enthusiasts",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Try tasting flights (4x 150ml glasses each) to sample different beers and find your favourite",
    "fun_facts": "Partners with Kazan Artisan brewery. Impressive selection of 6 taps featuring local brews. Reviews praise intimate atmosphere and friendly staff who make you feel at home."
  },
  {
    "category_id": 1,
    "name": "KANAAL",
    "meta": "🍺 Craft Beer · 38 Sorten · 5 Min Taxi ostwärts",
    "rating": 4.7,
    "price_range": null,
    "lat": 42.6959028,
    "lng": 23.347275,
    "website_url": "https://kanaal.bg",
    "address": "bul. Madrid 2, 1505 Sofia",
    "opening_hours": "Mon-Sun 17:30-01:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 285 6346",
    "beer_menu": "[{\"name\": \"13 rotierende Zapfhähne\", \"note\": \"bulgarisch & international, wechselt wöchentlich\", \"price\": \"7–12 BGN / 0.33L\"}, {\"name\": \"Sofia Electric Brewing\", \"style\": \"Lokale Brauerei, IPA & Pale Ale\", \"price\": \"8–10 BGN\"}, {\"name\": \"Meltum\", \"style\": \"Bulg. Craft-Brauerei\", \"price\": \"8 BGN\"}, {\"name\": \"Belgische Ales (Flasche)\", \"price\": \"10–15 BGN\"}, {\"name\": \"Mikkeler / BrewDog (Flasche)\", \"price\": \"12–18 BGN\", \"note\": \"wechselnd\"}]",
    "cocktails_menu": "[{\"name\": \"Rakia cocktails\", \"price\": \"varies\"}]",
    "food_menu": null,
    "music_type": "Live music, DJ events",
    "crowd_type": "Craft beer enthusiasts, Locals, Tourists",
    "seating_options": "[\"indoor\", \"terrace\"]",
    "pro_tips": "38 Zapfhähne mit internationalen und bulgarischen Crafts. Terrasse im Sommer extrem beliebt — früh kommen. Eigenes Kanaal-Bier unbedingt probieren.",
    "fun_facts": "Einer der ersten Craft-Beer-Bars Sofias — seit 2011. \"Kanaal\" = Kanal auf Niederländisch/Bulgarisch, inspiriert von der Industrieästhetik. Eigene Biermarke. Begrünte Wände + Vintage-Elemente im Innenraum."
  },
  {
    "category_id": 1,
    "name": "BiraBar",
    "meta": "🍺 Craft Beer · 13 Taps · auch Cask Ale",
    "rating": 4.6,
    "price_range": null,
    "lat": 42.6955,
    "lng": 23.3335,
    "website_url": null,
    "address": "ul. Paris 8, Sofia",
    "opening_hours": "Mo–Fr 12:30–23:00, Sa–So 14:00–23:30",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"13 Zapfhähne (rotierend)\", \"note\": \"Bulgarische Craft + englisches Real Ale\", \"price\": \"8–12 BGN / Pint\"}, {\"name\": \"Cask Ale (Real Ale)\", \"style\": \"Einziges Cask Ale in Bulgarien\", \"price\": \"9–11 BGN / Pint\"}, {\"name\": \"Brewery 359\", \"style\": \"Bulg. Craft-Brauerei\", \"price\": \"8 BGN\"}, {\"name\": \"BrewDog (Flasche)\", \"price\": \"12–15 BGN\"}, {\"name\": \"Mikkeler (Flasche)\", \"price\": \"14–18 BGN\"}]",
    "cocktails_menu": null,
    "food_menu": null,
    "local_specialties": "[\"Cask Ale — erstes und einziges in Bulgarien\"]",
    "music_type": "Englischer Pub-Sound",
    "crowd_type": "Craft-Beer-Fans, Expats, Einheimische",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Cask Ale nach Londoner Standard — einzigartig in ganz Bulgarien. 13 Zapfhähne mit lokalen und internationalen Crafts. BrewDog & Mikkeler im Flaschenangebot.",
    "fun_facts": "Traditioneller englischer Micropub in Sofias Zentrum. Erste Bar in ganz Bulgarien, die Cask Ale nach echter englischer Pub-Methode zapft. Gegründet mit Mission: bulgarische Bierkultur auf britisches Niveau heben."
  },
  {
    "category_id": 1,
    "name": "Beer University",
    "meta": "Vitosha Blvd · bulg. Biere",
    "rating": 4.4,
    "price_range": null,
    "lat": 42.6922,
    "lng": 23.3192,
    "website_url": null,
    "address": null,
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Ariana\", \"style\": \"Sofias älteste Brauerei, Lager\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Bulgarische Craft Biere (rotierend)\", \"style\": \"IPA, Pale Ale, Weizen\", \"price\": \"7–9 BGN / 0.33L\"}, {\"name\": \"Importierte Biere (Flasche)\", \"price\": \"8–12 BGN\"}]",
    "cocktails_menu": null,
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Entspannt, Bierkneipe",
    "crowd_type": "Craft-Beer-Fans, Locals, Studenten",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Guter Anlaufpunkt für bulgarische Biere in der Nähe des Vitosha-Boulevards.",
    "fun_facts": null
  },
  {
    "category_id": 1,
    "name": "Halbite (Tri ushi)",
    "meta": "Biergarten · nah am Hotel",
    "rating": 4.3,
    "price_range": null,
    "lat": 42.6955805,
    "lng": 23.3168245,
    "website_url": "https://halbite.com",
    "address": "ul. Tri ushi 13, Sofia",
    "opening_hours": "Mo–So 11:00–24:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 878 737 782",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Craft Beer (rotierend, bulg. & import.)\", \"price\": \"7–10 BGN / 0.33L\"}, {\"name\": \"Flaschenbiere\", \"price\": \"6–12 BGN\", \"note\": \"gute Auswahl bulg. & internationaler Sorten\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Pub-Snacks und Beilagen\"}]",
    "local_specialties": null,
    "music_type": "Entspannt, Biergarten-Vibe",
    "crowd_type": "Einheimische, Studenten, Bierliebhaber",
    "seating_options": "[\"indoor\", \"garden\"]",
    "pro_tips": "Mehrere Etagen + Biergarten. Wenige Minuten vom Hotel Niky — ideal für den ersten oder letzten Abend. Bis Mitternacht geöffnet.",
    "fun_facts": "\"Halbite\" = Bierkrüge auf Bulgarisch. \"Tri Ushi\" = drei Ohren (lokaler Slang für: drei Bierflaschen gleichzeitig tragen). Teil der Halbite-Kette in Sofia."
  },
  {
    "category_id": 1,
    "name": "Halbite Beer Hall",
    "meta": "Hinterhof-Biergarten",
    "rating": 4.3,
    "price_range": null,
    "lat": 42.69,
    "lng": 23.3243,
    "website_url": "https://halbite.com",
    "address": "ul. Cherkovna 41, Oborishte, Sofia",
    "opening_hours": "Mo–So 11:00–24:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 2 841 2513",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Craft Beer (rotierend)\", \"price\": \"7–10 BGN / 0.33L\"}, {\"name\": \"Großes Bier-Sortiment\", \"note\": \"20+ Sorten Flasche & Zapfhahn\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Pub-Klassiker und Snacks\"}]",
    "local_specialties": null,
    "music_type": "Entspannt, Biergarten",
    "crowd_type": "Oborishte-Locals, Studenten, Familien",
    "seating_options": "[\"indoor\", \"garden\"]",
    "pro_tips": "Zweite Halbite-Location im Oborishte-Viertel — etwas ruhiger als die Zentrum-Filiale. Hinterhof-Biergarten im Sommer sehr beliebt.",
    "fun_facts": "Oborishte ist Sofias quirky Kreativviertel — Halbite hier ist echter Kiez-Treff abseits der Touristenpfade."
  },

  {
    "category_id": 1,
    "name": "Rock'nRolla",
    "meta": "Rock & Karaoke · Mi–Sa",
    "rating": 4.3,
    "price_range": null,
    "lat": 42.694429,
    "lng": 23.322546,
    "website_url": "https://rocknrolla.bg",
    "address": "ul. Graf Ignatiev 1, Sofia",
    "opening_hours": "Mi–So 21:00–04:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"5 BGN / 0.5L\"}, {\"name\": \"Heineken\", \"style\": \"Lager Flasche\", \"price\": \"6 BGN / 0.33L\"}, {\"name\": \"Shots & Spirits\", \"price\": \"4–6 BGN\", \"note\": \"Rock-Club-typische Auswahl\"}]",
    "cocktails_menu": null,
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Rock & Karaoke (2 Räume)",
    "crowd_type": "Rock-Fans, Karaoke-Enthusiasten, Partygänger",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Zwei Räume: großer Club-Raum mit DJ + VIP-Bereich, kleiner Karaoke-Raum. Bis 04:00 Uhr geöffnet — perfekte Endstation nach anderen Bars.",
    "fun_facts": "Sofias bekanntester Rockklub: 8 Riesenbildschirme, modernes Soundsystem. Eigener Karaoke-Raum. Zentral am Graf Ignatiev — ein Muss für Rockfans."
  },
  {
    "category_id": 1,
    "name": "Fabric 123",
    "meta": "Cocktail Bar · Speakeasy-Vibes",
    "rating": 4.5,
    "price_range": null,
    "lat": 42.690601,
    "lng": 23.319231,
    "website_url": null,
    "address": "Saborna Str., Sofia (unmarkierte Tür)",
    "opening_hours": "ab 18:00 täglich, bis spät",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Craft Biere\", \"price\": \"3–4 BGN in der Happy Hour\"}]",
    "cocktails_menu": "[{\"name\": \"Signature Cocktails mit bulg. Rakia & lokalen Kräutern\", \"price\": \"18–25 BGN (9–13€)\"}, {\"name\": \"Happy Hour Cocktails\", \"price\": \"8–12 BGN\", \"note\": \"täglich 18–20 Uhr\"}]",
    "food_menu": null,
    "local_specialties": "[\"Cocktails mit lokaler Rakia und bulgarischen Kräutern\"]",
    "music_type": "Jazz",
    "crowd_type": "Cocktail-Liebhaber, Date Night, Kreative",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Happy Hour 18–20 Uhr: Cocktails ab 8 BGN. Unmarkierte Tür — einfach rein. Jazz-Soundtrack, Backsteinwände, dunkles Ambiente.",
    "fun_facts": "Teil von Sofias wachsender Speakeasy-Bewegung. Cocktails mit hausgemachten Zutaten und lokalen Spirituosen — bulgarische Rakia trifft Bartenderhandwerk."
  },
  {
    "category_id": 1,
    "name": "One More Park Bar",
    "meta": "Park Bar · Entspannte Atmosphäre",
    "rating": 4.4,
    "price_range": null,
    "lat": 42.677044,
    "lng": 23.346861,
    "website_url": null,
    "address": "ul. Nezabravka 3-5, Borisova Gradina, Sofia",
    "opening_hours": "Mo–So 10:30–02:00",
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": "+359 88 242 9974",
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Craft Beer (rotierend)\", \"price\": \"7–9 BGN / 0.33L\"}, {\"name\": \"Parkterrassenfeeling\", \"note\": \"Ideal für Abendstunden im Borisova Gradina-Park\"}]",
    "cocktails_menu": "[{\"name\": \"Bar-Klassiker\", \"note\": \"volle Barauswahl\"}]",
    "food_menu": "[{\"name\": \"Snacks und Kleingerichte\"}]",
    "local_specialties": null,
    "music_type": "Entspannt, Park-Vibe",
    "crowd_type": "Park-Besucher, Familien tagsüber, Party-Crowd abends",
    "seating_options": "[\"indoor\", \"outdoor\"]",
    "pro_tips": "Mitten in Borisova Gradina — dem größten Park Sofias. Tagsüber Café-Vibe, abends Bar. Viel Außensitzfläche.",
    "fun_facts": "Borisova Gradina ist Sofias Zentralpark — 1,3 km² direkt beim Nationalstadion. One More Park Bar: moderne Ausstattung mitten im Grünen."
  },
  {
    "category_id": 1,
    "name": "The Hop Bar",
    "meta": "🍺 Craft Beer · 12 Taps · Rotierende Biere",
    "rating": 4.6,
    "price_range": null,
    "lat": 42.694500,
    "lng": 23.328000,
    "website_url": null,
    "address": null,
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"12 rotierende Zapfhähne\", \"note\": \"bulgarisch & international\", \"price\": \"7–10 BGN / 0.33L\"}, {\"name\": \"Sofia Electric Brewing\", \"style\": \"IPA, Pale Ale\", \"price\": \"8 BGN\"}, {\"name\": \"Kazan Artisan\", \"style\": \"Craft, rotierend\", \"price\": \"8 BGN\"}, {\"name\": \"Flaschenbiere (rotierend)\", \"price\": \"9–15 BGN\", \"note\": \"belgisch, deutsch, amerikanisch\"}]",
    "cocktails_menu": null,
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Entspannt, Craft-Beer-Bar",
    "crowd_type": "Craft-Beer-Fans, Locals",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "12 rotierende Taps — was aktuell läuft variiert wöchentlich. Immer nach dem Aktuellen fragen.",
    "fun_facts": null
  },
  {
    "category_id": 1,
    "name": "Bar 103",
    "meta": "Speakeasy · Versteckter Eingang",
    "rating": 4.7,
    "price_range": null,
    "lat": 42.692800,
    "lng": 23.324500,
    "website_url": null,
    "address": null,
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager\", \"price\": \"5 BGN\"}, {\"name\": \"Craft Beer (Flasche)\", \"price\": \"7–9 BGN\", \"note\": \"Bier vorhanden, aber Cocktails dominieren\"}]",
    "cocktails_menu": "[{\"name\": \"Signature Cocktails\", \"note\": \"Speakeasy-Bar\"}]",
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Gedämpft, Speakeasy-Vibe",
    "crowd_type": "Cocktail-Fans, Hipster",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Versteckter Eingang — nach dem unscheinbaren Schild Ausschau halten oder anklopfen.",
    "fun_facts": null
  },
  {
    "category_id": 1,
    "name": "Cheveremetza 10",
    "meta": "Weinbar · Bulgarische Weine",
    "rating": 4.8,
    "price_range": null,
    "lat": 42.698000,
    "lng": 23.326000,
    "website_url": null,
    "address": null,
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Kein Bier-Fokus\", \"note\": \"Weinbar — hier Bulgarischen Wein bestellen!\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Kleine Bissen und Antipasti\", \"note\": \"zum Wein\"}]",
    "local_specialties": "[\"Bulgarische Weine\"]",
    "music_type": "Ruhig, Weinbar",
    "crowd_type": "Weinliebhaber, Einheimische",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Fokus auf bulgarische Weine — ideal um die hiesige Weinkultur kennenzulernen.",
    "fun_facts": null
  },
  {
    "category_id": 1,
    "name": "Vino & Grazhdanka",
    "meta": "Weinbar · Antipasti",
    "rating": 4.5,
    "price_range": null,
    "lat": 42.696000,
    "lng": 23.323000,
    "website_url": null,
    "address": null,
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Kein Bier-Fokus\", \"note\": \"Weinbar — hier bulgarischen Wein nach Empfehlung der Bedienung bestellen\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Antipasti\", \"note\": \"zum Wein\"}]",
    "local_specialties": "[\"Weinauswahl mit Antipasti\"]",
    "music_type": "Ruhig, Weinbar",
    "crowd_type": "Weinliebhaber, Couples",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Klassische Sofia-Weinstube mit Antipasti — Wein und kleinen Bissen zum Entspannen.",
    "fun_facts": null
  },
  {
    "category_id": 1,
    "name": "Bunker Bar",
    "meta": "Underground Bar · Industrial Vibes",
    "rating": 4.4,
    "price_range": null,
    "lat": 42.693000,
    "lng": 23.325000,
    "website_url": null,
    "address": null,
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Zagorka\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Shots & Spirits\", \"price\": \"4–7 BGN\", \"note\": \"Günstigster Bunker Sofias — spät abends\"}]",
    "cocktails_menu": "[{\"name\": \"Klassische Cocktails\"}]",
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Underground, Industrial Sound",
    "crowd_type": "Alternative Crowd, Locals",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Industrial-Vibe im Kellergewölbe — für alle, die es roh und unglamourös mögen.",
    "fun_facts": null
  },
  {
    "category_id": 1,
    "name": "Zelka Bar",
    "meta": "Local Favorite · Gemütlich",
    "rating": 4.6,
    "price_range": null,
    "lat": 42.691000,
    "lng": 23.322000,
    "website_url": null,
    "address": null,
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Kamenitza\", \"style\": \"Lager vom Fass\", \"price\": \"4 BGN / 0.5L\"}, {\"name\": \"Craft Beer (rotierend)\", \"price\": \"7–9 BGN / 0.33L\"}, {\"name\": \"Cocktails\", \"price\": \"8–12 BGN\"}]",
    "cocktails_menu": null,
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Entspannt, Stammkneipe",
    "crowd_type": "Einheimische, Stammgäste",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Echter Local-Spot — Einheimische treffen sich hier nach der Arbeit.",
    "fun_facts": null
  },
  {
    "category_id": 1,
    "name": "Brick Bar",
    "meta": "🍺 Craft Beer · Ziegelwände · 8 Taps",
    "rating": 4.8,
    "price_range": null,
    "lat": 42.697000,
    "lng": 23.329000,
    "website_url": null,
    "address": null,
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"8 rotierende Zapfhähne\", \"note\": \"lokal & international\", \"price\": \"7–10 BGN / 0.33L\"}, {\"name\": \"Bulgarische Craft Biere\", \"style\": \"Sofia Electric, Kazan, Meltum\", \"price\": \"7–9 BGN\"}, {\"name\": \"Craft Beer Flaschen\", \"price\": \"9–14 BGN\"}]",
    "cocktails_menu": null,
    "food_menu": null,
    "local_specialties": null,
    "music_type": "Entspannt, Craft-Beer-Bar",
    "crowd_type": "Craft-Beer-Fans, Locals",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "8 rotierende Zapfhähne. Backsteinwände schaffen echte Kellerkneipen-Atmosphäre.",
    "fun_facts": null
  },
  {
    "category_id": 1,
    "name": "The Apartment",
    "meta": "Bar · Wohnzimmer-Atmosphäre",
    "rating": 4.5,
    "price_range": null,
    "lat": 42.695000,
    "lng": 23.327000,
    "website_url": null,
    "address": "ul. Neofit Rilski 68, Sofia",
    "opening_hours": null,
    "payment_methods": "[\"cash\", \"card\"]",
    "phone": null,
    "beer_menu": "[{\"name\": \"Trappistenbier\", \"note\": \"Auswahl belgischer Trappisten\"}, {\"name\": \"Craft & Flaschenbiere\"}]",
    "cocktails_menu": null,
    "food_menu": "[{\"name\": \"Vegane & vegetarische Snacks\", \"note\": \"frisch in der kleinen Küche\"}, {\"name\": \"Sweets & Cakes\"}, {\"name\": \"Selbstgemachter Himbeer-Wein\"}]",
    "local_specialties": "[\"Ayurvedische Drinks\", \"Hausgemachter Himbeer-Wein\"]",
    "music_type": "Akustik-Konzerte, Lesungen, Filmvorführungen",
    "crowd_type": "Kreative, Intellektuelle, Alternativer Kulturtreff",
    "seating_options": "[\"indoor\"]",
    "pro_tips": "Regelmäßig Lesungen, Akustik-Konzerte, Theateraufführungen, Ausstellungen und Filmvorführungen — Programm vorher auf Facebook checken. Free Wifi, Macs zur freien Nutzung.",
    "fun_facts": "Zwei ehemalige Wohnungen zu einem Bar-Kulturzentrum umgebaut. Jedes Zimmer anders eingerichtet: Sofas, Sessel, Orientalische Sitzpolster. Hausgemachter Himbeer-Wein — einzigartig in Sofia."
  },
  {
    "category_id": 3,
    "name": "EXE Club",
    "meta": "World-class electronic events · Techno & House",
    "rating": 4.6,
    "price_range": null,
    "lat": 42.693904,
    "lng": 23.336272
  },
  {
    "category_id": 3,
    "name": "Bunker Club",
    "meta": "Underground · Techno · Alternative Kultur",
    "rating": 4.4,
    "price_range": null,
    "lat": 42.682626,
    "lng": 23.321150
  },
  {
    "category_id": 3,
    "name": "Mixtape 5",
    "meta": "Electronic · DJ-Kultur · Musik-orientiert",
    "rating": 4.3,
    "price_range": null,
    "lat": 42.682986,
    "lng": 23.321148
  },
  {
    "category_id": 3,
    "name": "FOMO the club",
    "meta": "Trendig · House & Techno · Modern",
    "rating": 4.5,
    "price_range": null,
    "lat": 42.695525,
    "lng": 23.323131
  },
  {
    "category_id": 3,
    "name": "Gramophone",
    "meta": "Vinyl-Fokus · House · Analog",
    "rating": 4.4,
    "price_range": null,
    "lat": 42.697664,
    "lng": 23.328275
  },
  {
    "category_id": 9,
    "name": "WC Vitosha / Zentrum",
    "meta": "Kostenlos · Fußgängerzone",
    "rating": null,
    "price_range": null,
    "lat": 42.6959,
    "lng": 23.3256
  },
  {
    "category_id": 9,
    "name": "WC Angel Kanchev (unterirdisch)",
    "meta": "Kostenlos · Level -1",
    "rating": null,
    "price_range": null,
    "lat": 42.6923,
    "lng": 23.3223
  },
  {
    "category_id": 9,
    "name": "WC NDK Süd",
    "meta": "1 BGN · Rollstuhlgerecht",
    "rating": null,
    "price_range": null,
    "lat": 42.6886,
    "lng": 23.3202
  },
  {
    "category_id": 9,
    "name": "WC Pirotska",
    "meta": "Kostenlos · nahe Zentralmarkt",
    "rating": null,
    "price_range": null,
    "lat": 42.7002,
    "lng": 23.3192
  },
  {
    "category_id": 9,
    "name": "WC Stadtgarten",
    "meta": "Gebühr · Rollstuhlgerecht",
    "rating": null,
    "price_range": null,
    "lat": 42.6944,
    "lng": 23.3302
  },
  {
    "category_id": 9,
    "name": "WC Stadtgarten Ost",
    "meta": "Kostenlos",
    "rating": null,
    "price_range": null,
    "lat": 42.6898,
    "lng": 23.3344
  },
  {
    "category_id": 9,
    "name": "WC Borisova Gradina",
    "meta": "Kostenlos · Parkeingang",
    "rating": null,
    "price_range": null,
    "lat": 42.6866,
    "lng": 23.3391
  },
  {
    "category_id": 9,
    "name": "WC Sándor-Petőfi-Str.",
    "meta": "Kostenlos · südlich NDK",
    "rating": null,
    "price_range": null,
    "lat": 42.6875,
    "lng": 23.3136
  },
  {
    "category_id": 9,
    "name": "WC Stambolov Blvd",
    "meta": "Gebühr · Mo–Sa 9–18, So 9–17 Uhr",
    "rating": null,
    "price_range": null,
    "lat": 42.7030,
    "lng": 23.3198,
    "opening_hours": "Mo–Sa 09:00–18:00, So 09:00–17:00"
  },
  {
    "category_id": 9,
    "name": "WC Pencho-Slaveykov-Blvd",
    "meta": "Gebühr · südlich Hotel",
    "rating": null,
    "price_range": null,
    "lat": 42.6830,
    "lng": 23.3180
  },
  {
    "category_id": 9,
    "name": "WC Dimitar Petkov",
    "meta": "Centrum",
    "rating": null,
    "price_range": null,
    "lat": 42.7005,
    "lng": 23.3005
  },
  {
    "category_id": 9,
    "name": "WC Hashove",
    "meta": "Razasadnik Konjovitsa",
    "rating": null,
    "price_range": null,
    "lat": 42.6963,
    "lng": 23.2934
  },
  {
    "category_id": 9,
    "name": "WC Hadzhi Dimitar",
    "meta": "Doncho Vatah",
    "rating": null,
    "price_range": null,
    "lat": 42.7069,
    "lng": 23.3513
  },
  {
    "category_id": 9,
    "name": "WC Poduene",
    "meta": "Han Omurtag",
    "rating": null,
    "price_range": null,
    "lat": 42.6914,
    "lng": 23.3443
  },
  {
    "category_id": 9,
    "name": "WC Maria Luisa Blvd Nord",
    "meta": "Kostenlos · Mo–So 6:30–18 Uhr",
    "rating": null,
    "price_range": null,
    "lat": 42.7114,
    "lng": 23.3201,
    "opening_hours": "Mo–So 06:30–18:00"
  },
  {
    "category_id": 9,
    "name": "WC Zona B-18",
    "meta": "Dimitar Petkov",
    "rating": null,
    "price_range": null,
    "lat": 42.7041,
    "lng": 23.3015
  },
  {
    "category_id": 9,
    "name": "WC Maria Luisa Blvd (unterirdisch)",
    "meta": "Gebühr · Level -1 · Rollstuhlgerecht",
    "rating": null,
    "price_range": null,
    "lat": 42.7121,
    "lng": 23.3213
  },
  {
    "category_id": 9,
    "name": "WC Zona B-5",
    "meta": "1 BGN · Mo–So 6–23 Uhr",
    "rating": null,
    "price_range": null,
    "lat": 42.6947,
    "lng": 23.3069,
    "opening_hours": "Mo–So 06:00–23:00"
  },
  {
    "category_id": 9,
    "name": "WC Stara Stena (Lozenets)",
    "meta": "Gebühr",
    "rating": null,
    "price_range": null,
    "lat": 42.6838,
    "lng": 23.3298
  },
  {
    "category_id": 9,
    "name": "WC Krakra",
    "meta": "Kostenlos · mobil",
    "rating": null,
    "price_range": null,
    "lat": 42.6945,
    "lng": 23.3376
  },
  {
    "category_id": 9,
    "name": "WC Skopie (Banishora)",
    "meta": "Kostenlos",
    "rating": null,
    "price_range": null,
    "lat": 42.7112,
    "lng": 23.3022
  },
  {
    "category_id": 9,
    "name": "WC Republika (Lev Tolstoi)",
    "meta": "Kostenlos · Mo–So 8–22 Uhr",
    "rating": null,
    "price_range": null,
    "lat": 42.7241,
    "lng": 23.3061,
    "opening_hours": "Mo–So 08:00–22:00"
  },
  {
    "category_id": 9,
    "name": "WC Gen. Danail Nikolaev",
    "meta": "Gebühr · Rollstuhlgerecht",
    "rating": null,
    "price_range": null,
    "lat": 42.7099,
    "lng": 23.3237
  },
  {
    "category_id": 9,
    "name": "WC Gen. Danail Nikolaev (2)",
    "meta": "Gebühr · Rollstuhlgerecht",
    "rating": null,
    "price_range": null,
    "lat": 42.7104,
    "lng": 23.3230
  },
  {
    "category_id": 9,
    "name": "WC Slivnitsa Blvd",
    "meta": "Gebühr",
    "rating": null,
    "price_range": null,
    "lat": 42.7044,
    "lng": 23.3309
  },
  {
    "category_id": 9,
    "name": "WC Zaharna Fabrika",
    "meta": "Nordwest Sofia",
    "rating": null,
    "price_range": null,
    "lat": 42.7138,
    "lng": 23.2847
  },
  {
    "category_id": 9,
    "name": "WC Sredets (mobil)",
    "meta": "Kostenlos · mobil",
    "rating": null,
    "price_range": null,
    "lat": 42.6879,
    "lng": 23.3370
  },
  {
    "category_id": 9,
    "name": "WC Ralitsa (Lozenets)",
    "meta": "Kostenlos · mobil",
    "rating": null,
    "price_range": null,
    "lat": 42.6828,
    "lng": 23.3238
  },
  {
    "category_id": 9,
    "name": "WC Rusalski Lak",
    "meta": "Suhata Reka",
    "rating": null,
    "price_range": null,
    "lat": 42.7034,
    "lng": 23.3602
  },
  {
    "category_id": 9,
    "name": "WC Belogradchik",
    "meta": "TEC Sofia",
    "rating": null,
    "price_range": null,
    "lat": 42.7111,
    "lng": 23.3226
  },
  {
    "category_id": 9,
    "name": "WC Nishava (Strelbishte)",
    "meta": "Kostenlos · Rollstuhlgerecht",
    "rating": null,
    "price_range": null,
    "lat": 42.6720,
    "lng": 23.2998
  },
  {
    "category_id": 9,
    "name": "WC Hubcha (Krasno Selo)",
    "meta": "Südwest Sofia",
    "rating": null,
    "price_range": null,
    "lat": 42.6775,
    "lng": 23.2860
  },
  {
    "category_id": 9,
    "name": "WC Balsha (Ivan Vazov)",
    "meta": "Gebühr",
    "rating": null,
    "price_range": null,
    "lat": 42.6771,
    "lng": 23.3039
  },
  {
    "category_id": 9,
    "name": "WC Voenna Rampa",
    "meta": "Kostenlos · Nordbezirk",
    "rating": null,
    "price_range": null,
    "lat": 42.7267,
    "lng": 23.3165
  },
  {
    "category_id": 9,
    "name": "WC Slivnitsa Blvd (2)",
    "meta": "Centrum Nord",
    "rating": null,
    "price_range": null,
    "lat": 42.7062,
    "lng": 23.3051
  },
  {
    "category_id": 9,
    "name": "WC BAN / Kaishev-Str.",
    "meta": "Ostrand Sofia",
    "rating": null,
    "price_range": null,
    "lat": 42.6756,
    "lng": 23.3659
  },
  {
    "category_id": 9,
    "name": "WC Hristo Smirnenski",
    "meta": "Kostenlos · Rollstuhlgerecht",
    "rating": null,
    "price_range": null,
    "lat": 42.6795,
    "lng": 23.3674
  },
  {
    "category_id": 9,
    "name": "WC Stambolov Blvd (2)",
    "meta": "Gebühr",
    "rating": null,
    "price_range": null,
    "lat": 42.7040,
    "lng": 23.3215
  },
  {
    "category_id": 9,
    "name": "WC Gen. Totleben Blvd",
    "meta": "Kostenlos · Rollstuhlgerecht",
    "rating": null,
    "price_range": null,
    "lat": 42.6896,
    "lng": 23.3021
  },
  {
    "category_id": 9,
    "name": "WC Maria Luisa Blvd",
    "meta": "Gebühr",
    "rating": null,
    "price_range": null,
    "lat": 42.7124,
    "lng": 23.3200
  },
  {
    "category_id": 9,
    "name": "WC Yuzhen Park",
    "meta": "Kostenlos",
    "rating": null,
    "price_range": null,
    "lat": 42.6716,
    "lng": 23.3111
  },
  {
    "category_id": 9,
    "name": "WC Arsenalski Blvd (Lozenets)",
    "meta": "Kostenlos · Rollstuhlgerecht",
    "rating": null,
    "price_range": null,
    "lat": 42.6788,
    "lng": 23.3204
  },
  {
    "category_id": 9,
    "name": "WC Hipodruma",
    "meta": "Vruh Tumba",
    "rating": null,
    "price_range": null,
    "lat": 42.6829,
    "lng": 23.2966
  },
  {
    "category_id": 9,
    "name": "WC Arsenalski Blvd Süd",
    "meta": "Kostenlos",
    "rating": null,
    "price_range": null,
    "lat": 42.6785,
    "lng": 23.3200
  }
]
