// Seed data extracted from sofia-guide-v6.html
// Source: trip guide for Sofia, 15-17 May 2026

export const categories = [
  { id: 1, name: "Sehenswürdigkeiten", color: "#C2185B", icon: "sight" },
  { id: 2, name: "Restaurants",        color: "#3B6D11", icon: "food"  },
  { id: 3, name: "Kneipen & Bars",     color: "#9B2915", icon: "bar"   },
  { id: 4, name: "Craft Beer",         color: "#185FA5", icon: "beer"  },
  { id: 5, name: "Nightlife",          color: "#2c2c2a", icon: "night" },
  { id: 6, name: "Hotel",              color: "#E5A038", icon: "hotel" },
];

export const locations = [
  // ── Hotel ─────────────────────────────────────────────────────────────────
  {
    category_id: 6,
    name: "Hotel Niky",
    meta: "Neofit Rilski 16 · +359 2 952 3058",
    rating: null,
    price_range: null,
    lat: 42.6953,
    lng: 23.3219,
  },

  // ── Sehenswürdigkeiten ────────────────────────────────────────────────────
  {
    category_id: 1,
    name: "Alexander-Newski-Kathedrale",
    meta: "Wahrzeichen · goldene Kuppeln",
    rating: null,
    price_range: null,
    lat: 42.6959,
    lng: 23.3330,
  },
  {
    category_id: 1,
    name: "Rotunde Hl. Georg",
    meta: "4. Jh. · älteste Kirche Sofias",
    rating: null,
    price_range: null,
    lat: 42.6964,
    lng: 23.3247,
  },
  {
    category_id: 1,
    name: "Sveta Sofia Kirche",
    meta: "6. Jh. · Namensgeberin der Stadt",
    rating: null,
    price_range: null,
    lat: 42.6961,
    lng: 23.3325,
  },
  {
    category_id: 1,
    name: "Sveta Nedelya Kathedrale",
    meta: "Zentraler Platz · Bombengeschichte",
    rating: null,
    price_range: null,
    lat: 42.6963,
    lng: 23.3214,
  },
  {
    category_id: 1,
    name: "Banya Bashi Moschee",
    meta: "16. Jh. · über heißen Quellen",
    rating: null,
    price_range: null,
    lat: 42.6973,
    lng: 23.3213,
  },
  {
    category_id: 1,
    name: "Russische Kirche St. Nikolaus",
    meta: "Zwiebelkuppeln · Moskauer Stil",
    rating: null,
    price_range: null,
    lat: 42.6954,
    lng: 23.3304,
  },
  {
    category_id: 1,
    name: "Ivan Vazov Nationaltheater",
    meta: "Neoklassizismus · abends beleuchtet",
    rating: null,
    price_range: null,
    lat: 42.6944,
    lng: 23.3280,
  },
  {
    category_id: 1,
    name: "Ancient Serdica (Ruinen)",
    meta: "Römerzeit · frei zugänglich",
    rating: null,
    price_range: null,
    lat: 42.6964,
    lng: 23.3226,
  },
  {
    category_id: 1,
    name: "Mineralbad & Stadtmuseum",
    meta: "Jugendstil · Gratis-Heilquellen",
    rating: null,
    price_range: null,
    lat: 42.6972,
    lng: 23.3225,
  },
  {
    category_id: 1,
    name: "Vitosha Boulevard",
    meta: "Flaniermeile · Fußgängerzone",
    rating: null,
    price_range: null,
    lat: 42.6921,
    lng: 23.3200,
  },
  {
    category_id: 1,
    name: "Crystal Garden",
    meta: "Stadtpark · Touren-Treffpunkt",
    rating: null,
    price_range: null,
    lat: 42.6953,
    lng: 23.3315,
  },
  {
    category_id: 1,
    name: "Zentralsynagoge",
    meta: "Größte Sephardischer Europas",
    rating: null,
    price_range: null,
    lat: 42.6969,
    lng: 23.3205,
  },

  // ── Restaurants ───────────────────────────────────────────────────────────
  {
    category_id: 2,
    name: "Cosmos",
    meta: "Bulg. Fusion, Fine Dining",
    rating: 4.6,
    price_range: "€€€",
    lat: 42.6933,
    lng: 23.3185,
  },
  {
    category_id: 2,
    name: "Supa Star",
    meta: "Suppen · Lunch-Geheimtipp",
    rating: 4.6,
    price_range: "€",
    lat: 42.6951,
    lng: 23.3352,
  },
  {
    category_id: 2,
    name: "Hadjidraganov's Houses",
    meta: "Traditionell, Live-Musik",
    rating: 4.5,
    price_range: "€€",
    lat: 42.7012,
    lng: 23.3224,
  },
  {
    category_id: 2,
    name: "Shtastlivetsa",
    meta: "Klassiker am Vitosha Blvd",
    rating: 4.5,
    price_range: "€€",
    lat: 42.6924,
    lng: 23.3196,
  },
  {
    category_id: 2,
    name: "Pastorant",
    meta: "Italienisch, intim · So zu",
    rating: 4.5,
    price_range: "€€",
    lat: 42.6922,
    lng: 23.3183,
  },
  {
    category_id: 2,
    name: "Checkpoint Charly",
    meta: "Berlin-Vibes · bulg. Küche",
    rating: 4.4,
    price_range: "€€",
    lat: 42.6942,
    lng: 23.3272,
  },
  {
    category_id: 2,
    name: "Manastirska Magernitsa",
    meta: "Klosterküche · 200+ Gerichte",
    rating: 4.3,
    price_range: "€€",
    lat: 42.6910,
    lng: 23.3250,
  },
  {
    category_id: 2,
    name: "Made in Home / Dark Sister",
    meta: "Modern · Mo+Di zu",
    rating: 4.3,
    price_range: "€€",
    lat: 42.6898,
    lng: 23.3240,
  },
  {
    category_id: 2,
    name: "Moma Bulgarian Food",
    meta: "Bulg. Küche & Wein",
    rating: 4.2,
    price_range: "€€",
    lat: 42.6920,
    lng: 23.3178,
  },
  {
    category_id: 2,
    name: "Divaka",
    meta: "Groß, laut, traditionell",
    rating: 4.1,
    price_range: "€€",
    lat: 42.6919,
    lng: 23.3200,
  },
  {
    category_id: 2,
    name: "Skapto Burgers & Beer",
    meta: "Handgemachte Burger",
    rating: 4.4,
    price_range: "€€",
    lat: 42.6950,
    lng: 23.3320,
  },
  {
    category_id: 2,
    name: "Sun Moon",
    meta: "Vegetarisch / vegan",
    rating: 4.4,
    price_range: "€€",
    lat: 42.6908,
    lng: 23.3247,
  },

  // ── Kneipen & Bars ────────────────────────────────────────────────────────
  {
    category_id: 3,
    name: "Hambara",
    meta: "Versteckt, Kerzenlicht · bis 03",
    rating: 4.3,
    price_range: null,
    lat: 42.6905,
    lng: 23.3210,
  },
  {
    category_id: 3,
    name: "Raketa Rakia Bar",
    meta: "30+ Rakias · Sowjet-Deko",
    rating: 4.5,
    price_range: null,
    lat: 42.6992,
    lng: 23.3380,
  },
  {
    category_id: 3,
    name: "Sputnik Cocktail Bar",
    meta: "Kreativ-Cocktails · neben K2",
    rating: 4.7,
    price_range: null,
    lat: 42.6992,
    lng: 23.3380,
  },
  {
    category_id: 3,
    name: "Eddie Sicoy Bar",
    meta: "Guinness vom Hahn · funky",
    rating: 4.7,
    price_range: null,
    lat: 42.6901,
    lng: 23.3188,
  },
  {
    category_id: 3,
    name: "Bar Locál",
    meta: "Kleine Cocktail-Kunstwerke",
    rating: 4.6,
    price_range: null,
    lat: 42.6905,
    lng: 23.3230,
  },
  {
    category_id: 3,
    name: "Bar Secret Room",
    meta: "Versteckt · Mi–Sa bis 05",
    rating: 4.2,
    price_range: null,
    lat: 42.6923,
    lng: 23.3215,
  },
  {
    category_id: 3,
    name: "Caldo Whiskey & Friends",
    meta: "Riesige Whiskey-Auswahl",
    rating: 4.6,
    price_range: null,
    lat: 42.6940,
    lng: 23.3295,
  },
  {
    category_id: 3,
    name: "Sip'n Bite Wine Spot",
    meta: "Bulg. Weine · Antipasti",
    rating: 5.0,
    price_range: null,
    lat: 42.6928,
    lng: 23.3175,
  },
  {
    category_id: 3,
    name: "La Cave du Moulin",
    meta: "Franz. Wein aus Dispenser",
    rating: 4.8,
    price_range: null,
    lat: 42.6922,
    lng: 23.3183,
  },

  // ── Craft Beer ────────────────────────────────────────────────────────────
  {
    category_id: 4,
    name: "Tap Local",
    meta: "6 Hähne, Top-Qualität",
    rating: 4.9,
    price_range: null,
    lat: 42.6940,
    lng: 23.3295,
  },
  {
    category_id: 4,
    name: "KANAAL",
    meta: "38 Sorten · 5 Min Taxi ostwärts",
    rating: 4.7,
    price_range: null,
    lat: 42.6950,
    lng: 23.3400,
  },
  {
    category_id: 4,
    name: "BiraBar",
    meta: "13 Taps · auch Cask Ale",
    rating: 4.6,
    price_range: null,
    lat: 42.6955,
    lng: 23.3335,
  },
  {
    category_id: 4,
    name: "Beer University",
    meta: "Vitosha Blvd · bulg. Biere",
    rating: 4.4,
    price_range: null,
    lat: 42.6922,
    lng: 23.3192,
  },
  {
    category_id: 4,
    name: "Halbite (Tri ushi)",
    meta: "Biergarten · nah am Hotel",
    rating: 4.3,
    price_range: null,
    lat: 42.6935,
    lng: 23.3175,
  },
  {
    category_id: 4,
    name: "Halbite Beer Hall",
    meta: "Hinterhof-Biergarten",
    rating: 4.3,
    price_range: null,
    lat: 42.6900,
    lng: 23.3243,
  },

  // ── Nightlife ─────────────────────────────────────────────────────────────
  {
    category_id: 5,
    name: "Carrusel Club",
    meta: "Do–Sa bis 06 · Dance",
    rating: 4.4,
    price_range: null,
    lat: 42.6930,
    lng: 23.3278,
  },
  {
    category_id: 5,
    name: "Rock'nRolla",
    meta: "Rock & Karaoke · Mi–Sa",
    rating: 4.3,
    price_range: null,
    lat: 42.6960,
    lng: 23.3218,
  },
  {
    category_id: 5,
    name: "Yalta",
    meta: "Retro-Beats · intensiv laut",
    rating: 4.2,
    price_range: null,
    lat: 42.6950,
    lng: 23.3375,
  },
];
